In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import warnings

warnings.filterwarnings("ignore", category=UserWarning)

# sys.path.insert(0, "/Users/poorna/Downloads/CE-updated/calibrated_explanations/src")

# Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from calibrated_explanations import WrapCalibratedExplainer, __version__

print(f"calibrated_explanations {__version__}")

calibrated_explanations v0.11.1

In [3]:
# Load and preprocess the data
num_to_test = 10  # number of instances to test, one from each class
dataset = "diabetes_full"
delimiter = ","
model = "RF"

filename = "../../data/diabetes_full.csv"
df = pd.read_csv(filename, delimiter=delimiter)
target = "Y"
X, y = df.drop(target, axis=1), df[target]
no_of_classes = len(np.unique(y))
no_of_features = X.shape[1]
no_of_instances = X.shape[0]

# find categorical features
categorical_features = [i for i in range(no_of_features) if len(np.unique(X.iloc[:, i])) < 10]

# select test instances from each class and split into train, cal and test
idx = np.argsort(y.values).astype(int)
X, y = X.values[idx, :], y.values[idx]
test_index = np.array(
    [
        *range(int(num_to_test / 2)),
        *range(no_of_instances - 1, no_of_instances - int(num_to_test / 2) - 1, -1),
    ]
)
train_index = np.setdiff1d(np.array(range(no_of_instances)), test_index)
x_train, x_test = X[train_index, :], X[test_index, :]
y_train, y_test = y[train_index], y[test_index]
X_prop_train, x_cal, y_prop_train, y_cal = train_test_split(
    x_train, y_train, test_size=0.33, random_state=42, stratify=y_train
)

In [4]:
# Train the model and create the explainer
model = RandomForestClassifier()

model.fit(X_prop_train, y_prop_train)

ce = WrapCalibratedExplainer(model)
ce.calibrate(x_cal, y_cal, feature_names=df.columns, categorical_features=categorical_features, class_labels={0: "Non-diabetic", 1: "Diabetic"})

C:\Users\loftuw\AppData\Local\Python\pythoncore-3.14-64\Lib\importlib\__init__.py:88: UserWarning: Cache backend fallback: using minimal in-package LRU/TTL implementation due to missing 'cachetools'
  return _bootstrap._gcd_import(name[level:], package, level)

WrapCalibratedExplainer(learner=RandomForestClassifier(), fitted=True, calibrated=True,
		explainer=CalibratedExplainer(mode=classification, learner=RandomForestClassifier()))

In [5]:
factual_explanations = ce.explain_factual(x_test)
print("Probability [lower and upper bound] for Diabetic:")
print(
    *zip(
        [
            f"Instance {i}: {exp.prediction['predict']:.3f} [{exp.prediction['low']:5.3f}, {exp.prediction['high']:5.3f}]"
            for i, exp in enumerate(factual_explanations)
        ], strict=False
    ),
    sep="\n",
)

Probability [lower and upper bound] for Diabetic:
('Instance 0: 0.367 [0.348, 0.378]',)
('Instance 1: 0.550 [0.542, 0.559]',)
('Instance 2: 0.437 [0.356, 0.500]',)
('Instance 3: 0.062 [0.032, 0.065]',)
('Instance 4: 0.550 [0.542, 0.559]',)
('Instance 5: 0.378 [0.356, 0.391]',)
('Instance 6: 0.550 [0.542, 0.559]',)
('Instance 7: 0.550 [0.542, 0.559]',)
('Instance 8: 0.719 [0.688, 0.800]',)
('Instance 9: 0.188 [0.162, 0.194]',)

Example demonstrating the new to_narrative API.

This shows the clean API for generating narratives from calibrated explanations.

In [6]:
# The new to_narrative method provides a clean API:
explanations = factual_explanations

# Basic usage
narratives = explanations[0].to_narrative(
    expertise_level=("beginner", "advanced"),
    output_format="text",
)
print(narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Advanced):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.367
Prediction Interval: [0.348, 0.378]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (145.0) > 122.50                — weight ≈ 0.191 [0.186, 0.212]
Pregnancies (13.0) > 6.50               — weight ≈ 0.179 [0.173, 0.205]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (22.2) <= 26.70                     — weight ≈ -0.183 [-0.193, -0.176]
DiabetesPedigreeFunction (0.24) <= 0.53 — weight ≈ -0.071 [-0.133, 0.008] [⚠️ direction uncertain]
Insulin (110.0) <= 192.50               — weight ≈ -0.050 [-0.097, 0.011] [⚠️ direction uncertain]
BloodPressure (82.0) > 69.00            — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]
SkinThickness (19.0) <= 32.50           — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.367

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 122.50
* Pregnancies (13.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 26.70
* DiabetesPedigreeFunction (0.24) <= 0.53 [⚠️ direction uncertain]
* Insulin (110.0) <= 192.50 [⚠️ direction uncertain]
* BloodPressure (82.0) > 69.00 [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50 [⚠️ direction uncertain]

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanation.py:668: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  result = plugin.plot(

In [7]:
# Different output formats:

# 1. DataFrame (default) - returns pandas DataFrame
df_narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="markdown"
)
print(df_narratives)

## Instance 0

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.367
Prediction Interval: [0.348, 0.378]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (145.0) > 122.50                — weight ≈ 0.191 [0.186, 0.212]
Pregnancies (13.0) > 6.50               — weight ≈ 0.179 [0.173, 0.205]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (22.2) <= 26.70                     — weight ≈ -0.183 [-0.193, -0.176]
DiabetesPedigreeFunction (0.24) <= 0.53 — weight ≈ -0.071 [-0.133, 0.008] [⚠️ direction uncertain]
Insulin (110.0) <= 192.50               — weight ≈ -0.050 [-0.097, 0.011] [⚠️ direction uncertain]
BloodPressure (82.0) > 69.00            — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]
SkinThickness (19.0) <= 32.50           — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.367

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 122.50
* Pregnancies (13.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 26.70
* DiabetesPedigreeFunction (0.24) <= 0.53 [⚠️ direction uncertain]
* Insulin (110.0) <= 192.50 [⚠️ direction uncertain]
* BloodPressure (82.0) > 69.00 [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50 [⚠️ direction uncertain]
```

## Instance 1

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.550
Prediction Interval: [0.542, 0.559]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (34.1) > 26.70           — weight ≈ 0.365 [0.359, 0.392]
Age (38.0) > 27.50           — weight ≈ 0.180 [0.168, 0.200]
SkinThickness (0.0) <= 32.50 — weight ≈ 0.172 [0.159, 0.194]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (117.0) <= 122.50    — weight ≈ -0.133 [-0.217, -0.094]
BloodPressure (92.0) > 69.00 — weight ≈ -0.053 [-0.086, -0.034]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 26.70
* Age (38.0) > 27.50
* SkinThickness (0.0) <= 32.50

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 69.00
```

## Instance 2

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.437
Prediction Interval: [0.356, 0.500]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (36.0) > 26.70                     — weight ≈ 0.267 [0.264, 0.283]
Age (60.0) > 27.50                     — weight ≈ 0.251 [0.245, 0.277]
DiabetesPedigreeFunction (0.55) > 0.53 — weight ≈ 0.066 [0.055, 0.086]
BloodPressure (75.0) > 69.00           — weight ≈ 0.059 [0.046, 0.081]
SkinThickness (26.0) <= 32.50          — weight ≈ 0.019 [-0.027, 0.078] [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (109.0) <= 122.50              — weight ≈ -0.318 [-0.379, -0.297]
Pregnancies (5.0) <= 6.50              — weight ≈ -0.113 [-0.122, -0.105]
Insulin (0.0) <= 192.50                — weight ≈ -0.091 [-0.122, -0.063]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.437

Factors impacting the probability for class Diabetic positively:
* BMI (36.0) > 26.70
* Age (60.0) > 27.50
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 69.00
* SkinThickness (26.0) <= 32.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* Pregnancies (5.0) <= 6.50
* Insulin (0.0) <= 192.50
```

## Instance 3

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.062
Prediction Interval: [0.032, 0.065]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (108.0) <= 122.50               — weight ≈ -0.162 [-0.187, -0.095]
BMI (26.0) <= 26.70                     — weight ≈ -0.120 [-0.125, -0.095]
Pregnancies (3.0) <= 6.50               — weight ≈ -0.116 [-0.121, -0.092]
Age (25.0) <= 27.50                     — weight ≈ -0.114 [-0.118, -0.092]
SkinThickness (24.0) <= 32.50           — weight ≈ -0.108 [-0.111, -0.091]
Insulin (0.0) <= 192.50                 — weight ≈ -0.099 [-0.107, -0.051]
BloodPressure (62.0) <= 69.00           — weight ≈ -0.036 [-0.038, -0.010]
DiabetesPedigreeFunction (0.22) <= 0.53 — weight ≈ -0.027 [-0.035, 0.030] [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* Glucose (108.0) <= 122.50
* BMI (26.0) <= 26.70
* Pregnancies (3.0) <= 6.50
* Age (25.0) <= 27.50
* SkinThickness (24.0) <= 32.50
* Insulin (0.0) <= 192.50
* BloodPressure (62.0) <= 69.00
* DiabetesPedigreeFunction (0.22) <= 0.53 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
```

## Instance 4

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.550
Prediction Interval: [0.542, 0.559]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (32.0) > 26.70                      — weight ≈ 0.183 [0.172, 0.202]
Glucose (137.0) > 122.50                — weight ≈ 0.139 [0.110, 0.197]
Age (39.0) > 27.50                      — weight ≈ 0.044 [0.010, 0.083]

Factors impacting the calibrated probability for class Diabetic negatively:
SkinThickness (41.0) > 32.50            — weight ≈ -0.110 [-0.161, -0.086]
DiabetesPedigreeFunction (0.39) <= 0.53 — weight ≈ -0.101 [-0.150, -0.075]
BloodPressure (90.0) > 69.00            — weight ≈ -0.012 [-0.036, 0.008] [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 26.70
* Glucose (137.0) > 122.50
* Age (39.0) > 27.50

Factors impacting the probability for class Diabetic negatively:
* SkinThickness (41.0) > 32.50
* DiabetesPedigreeFunction (0.39) <= 0.53
* BloodPressure (90.0) > 69.00 [⚠️ direction uncertain]
```

## Instance 5

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.378
Prediction Interval: [0.356, 0.391]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (30.0) > 26.70                      — weight ≈ 0.195 [0.189, 0.222]
Pregnancies (7.0) > 6.50                — weight ≈ 0.190 [0.184, 0.216]
Age (32.0) > 27.50                      — weight ≈ 0.011 [0.000, 0.030]
DiabetesPedigreeFunction (0.48) <= 0.53 — weight ≈ 0.007 [-0.004, 0.027] [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (100.0) <= 122.50               — weight ≈ -0.343 [-0.397, -0.322]
Insulin (0.0) <= 192.50                 — weight ≈ -0.061 [-0.122, 0.018] [⚠️ direction uncertain]
BloodPressure (0.0) <= 69.00            — weight ≈ -0.020 [-0.050, 0.021] [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.378

Factors impacting the probability for class Diabetic positively:
* BMI (30.0) > 26.70
* Pregnancies (7.0) > 6.50
* Age (32.0) > 27.50
* DiabetesPedigreeFunction (0.48) <= 0.53 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* Insulin (0.0) <= 192.50 [⚠️ direction uncertain]
* BloodPressure (0.0) <= 69.00 [⚠️ direction uncertain]
```

## Instance 6

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.550
Prediction Interval: [0.542, 0.559]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (166.0) > 122.50               — weight ≈ 0.362 [0.356, 0.388]
Age (51.0) > 27.50                     — weight ≈ 0.152 [0.122, 0.193]
DiabetesPedigreeFunction (0.59) > 0.53 — weight ≈ 0.118 [0.107, 0.135]
BloodPressure (72.0) > 69.00           — weight ≈ 0.102 [0.066, 0.146]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (25.8) <= 26.70                    — weight ≈ -0.199 [-0.249, -0.182]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* Age (51.0) > 27.50
* DiabetesPedigreeFunction (0.59) > 0.53
* BloodPressure (72.0) > 69.00

Factors impacting the probability for class Diabetic negatively:
* BMI (25.8) <= 26.70
```

## Instance 7

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.550
Prediction Interval: [0.542, 0.559]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (189.0) > 122.50               — weight ≈ 0.176 [0.163, 0.197]
BMI (30.1) > 26.70                     — weight ≈ 0.133 [0.086, 0.194]
Age (59.0) > 27.50                     — weight ≈ 0.115 [0.103, 0.132]

Factors impacting the calibrated probability for class Diabetic negatively:
Pregnancies (1.0) <= 6.50              — weight ≈ -0.180 [-0.241, -0.156]
BloodPressure (60.0) <= 69.00          — weight ≈ -0.160 [-0.233, -0.131]
SkinThickness (23.0) <= 32.50          — weight ≈ -0.074 [-0.150, -0.031]
DiabetesPedigreeFunction (0.4) <= 0.53 — weight ≈ -0.053 [-0.086, -0.034]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* Glucose (189.0) > 122.50
* BMI (30.1) > 26.70
* Age (59.0) > 27.50

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (1.0) <= 6.50
* BloodPressure (60.0) <= 69.00
* SkinThickness (23.0) <= 32.50
* DiabetesPedigreeFunction (0.4) <= 0.53
```

## Instance 8

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.719
Prediction Interval: [0.688, 0.800]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (168.0) > 122.50               — weight ≈ 0.384 [0.357, 0.427]
BMI (38.0) > 26.70                     — weight ≈ 0.169 [0.160, 0.177]
DiabetesPedigreeFunction (0.54) > 0.53 — weight ≈ 0.159 [0.116, 0.196]
BloodPressure (74.0) > 69.00           — weight ≈ 0.022 [-0.048, 0.052] [⚠️ direction uncertain]
Age (34.0) > 27.50                     — weight ≈ 0.018 [-0.064, 0.052] [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Insulin (0.0) <= 192.50                — weight ≈ -0.059 [-0.104, -0.046]
Pregnancies (10.0) > 6.50              — weight ≈ -0.059 [-0.104, -0.046]
SkinThickness (0.0) <= 32.50           — weight ≈ -0.039 [-0.097, -0.020]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.719

Factors impacting the probability for class Diabetic positively:
* Glucose (168.0) > 122.50
* BMI (38.0) > 26.70
* DiabetesPedigreeFunction (0.54) > 0.53
* BloodPressure (74.0) > 69.00 [⚠️ direction uncertain]
* Age (34.0) > 27.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Insulin (0.0) <= 192.50
* Pregnancies (10.0) > 6.50
* SkinThickness (0.0) <= 32.50
```

## Instance 9

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.188
Prediction Interval: [0.162, 0.194]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (125.0) > 122.50                — weight ≈ 0.002 [-0.004, 0.028] [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (0.0) <= 26.70                      — weight ≈ -0.231 [-0.276, -0.171]
BloodPressure (96.0) > 69.00            — weight ≈ -0.179 [-0.190, -0.160]
Insulin (0.0) <= 192.50                 — weight ≈ -0.179 [-0.190, -0.160]
SkinThickness (0.0) <= 32.50            — weight ≈ -0.179 [-0.190, -0.160]
Age (54.0) > 27.50                      — weight ≈ -0.159 [-0.187, -0.098]
DiabetesPedigreeFunction (0.23) <= 0.53 — weight ≈ -0.139 [-0.185, -0.036]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.188

Factors impacting the probability for class Diabetic positively:
* Glucose (125.0) > 122.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (0.0) <= 26.70
* BloodPressure (96.0) > 69.00
* Insulin (0.0) <= 192.50
* SkinThickness (0.0) <= 32.50
* Age (54.0) > 27.50
* DiabetesPedigreeFunction (0.23) <= 0.53
```

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [8]:
# 2. Text - returns formatted text string
text_narratives = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(text_narratives)
text_narratives = explanations.add_conjunctions(max_rule_size=3).to_narrative(
    expertise_level="beginner", output_format="text"
)
print(text_narratives)

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.367

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 122.50
* Pregnancies (13.0) > 6.50

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 26.70
* DiabetesPedigreeFunction (0.24) <= 0.53 [⚠️ direction uncertain]
* Insulin (110.0) <= 192.50 [⚠️ direction uncertain]
* BloodPressure (82.0) > 69.00 [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50 [⚠️ direction uncertain]

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 26.70
* Age (38.0) > 27.50
* SkinThickness (0.0) <= 32.50

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 69.00

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.437

Factors impacting the probability for class Diabetic positively:
* BMI (36.0) > 26.70
* Age (60.0) > 27.50
* DiabetesPedigreeFunction (0.55) > 0.53
* BloodPressure (75.0) > 69.00
* SkinThickness (26.0) <= 32.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* Pregnancies (5.0) <= 6.50
* Insulin (0.0) <= 192.50

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* Glucose (108.0) <= 122.50
* BMI (26.0) <= 26.70
* Pregnancies (3.0) <= 6.50
* Age (25.0) <= 27.50
* SkinThickness (24.0) <= 32.50
* Insulin (0.0) <= 192.50
* BloodPressure (62.0) <= 69.00
* DiabetesPedigreeFunction (0.22) <= 0.53 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 26.70
* Glucose (137.0) > 122.50
* Age (39.0) > 27.50

Factors impacting the probability for class Diabetic negatively:
* SkinThickness (41.0) > 32.50
* DiabetesPedigreeFunction (0.39) <= 0.53
* BloodPressure (90.0) > 69.00 [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.378

Factors impacting the probability for class Diabetic positively:
* BMI (30.0) > 26.70
* Pregnancies (7.0) > 6.50
* Age (32.0) > 27.50
* DiabetesPedigreeFunction (0.48) <= 0.53 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* Insulin (0.0) <= 192.50 [⚠️ direction uncertain]
* BloodPressure (0.0) <= 69.00 [⚠️ direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* Age (51.0) > 27.50
* DiabetesPedigreeFunction (0.59) > 0.53
* BloodPressure (72.0) > 69.00

Factors impacting the probability for class Diabetic negatively:
* BMI (25.8) <= 26.70

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* Glucose (189.0) > 122.50
* BMI (30.1) > 26.70
* Age (59.0) > 27.50

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (1.0) <= 6.50
* BloodPressure (60.0) <= 69.00
* SkinThickness (23.0) <= 32.50
* DiabetesPedigreeFunction (0.4) <= 0.53

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.719

Factors impacting the probability for class Diabetic positively:
* Glucose (168.0) > 122.50
* BMI (38.0) > 26.70
* DiabetesPedigreeFunction (0.54) > 0.53
* BloodPressure (74.0) > 69.00 [⚠️ direction uncertain]
* Age (34.0) > 27.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Insulin (0.0) <= 192.50
* Pregnancies (10.0) > 6.50
* SkinThickness (0.0) <= 32.50

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.188

Factors impacting the probability for class Diabetic positively:
* Glucose (125.0) > 122.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (0.0) <= 26.70
* BloodPressure (96.0) > 69.00
* Insulin (0.0) <= 192.50
* SkinThickness (0.0) <= 32.50
* Age (54.0) > 27.50
* DiabetesPedigreeFunction (0.23) <= 0.53

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.367

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 122.50
* Pregnancies (13.0) > 6.50
* (BloodPressure (82.0) > 69.00 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (BMI (22.2) <= 26.70 AND DiabetesPedigreeFunction (0.24) <= 0.53) [⚠️ direction uncertain]
* (BloodPressure (82.0) > 69.00 AND BMI (22.2) <= 26.70) [⚠️ direction uncertain]
* (Insulin (110.0) <= 192.50 AND DiabetesPedigreeFunction (0.24) <= 0.53) [⚠️ direction uncertain]
* (SkinThickness (19.0) <= 32.50 AND BMI (22.2) <= 26.70) [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Insulin (110.0) <= 192.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Pregnancies (13.0) > 6.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND Insulin (110.0) <= 192.50)
* BMI (22.2) <= 26.70
* (Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 26.70)
* (Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50)
* (BloodPressure (82.0) > 69.00 AND Pregnancies (13.0) > 6.50)
* DiabetesPedigreeFunction (0.24) <= 0.53 [⚠️ direction uncertain]
* Insulin (110.0) <= 192.50 [⚠️ direction uncertain]
* (BloodPressure (82.0) > 69.00 AND Insulin (110.0) <= 192.50)
* (Insulin (110.0) <= 192.50 AND BMI (22.2) <= 26.70)
* BloodPressure (82.0) > 69.00 [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50 [⚠️ direction uncertain]

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 26.70
* (BloodPressure (92.0) > 69.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* Age (38.0) > 27.50
* SkinThickness (0.0) <= 32.50
* (Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* (Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (BloodPressure (92.0) > 69.00 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)
* (BloodPressure (92.0) > 69.00 AND Age (38.0) > 27.50)
* (BloodPressure (92.0) > 69.00 AND SkinThickness (0.0) <= 32.50)

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 69.00
* (BMI (34.1) > 26.70 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 26.70)

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.437

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (5.0) <= 6.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (BloodPressure (75.0) > 69.00 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (BMI (36.0) > 26.70 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BMI (36.0) > 26.70 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (Glucose (109.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (BMI (36.0) > 26.70 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* BMI (36.0) > 26.70
* (BMI (36.0) > 26.70 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Glucose (109.0) <= 122.50 AND BMI (36.0) > 26.70)
* Age (60.0) > 27.50
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Age (60.0) > 27.50)
* (Pregnancies (5.0) <= 6.50 AND BMI (36.0) > 26.70)
* (BloodPressure (75.0) > 69.00 AND Pregnancies (5.0) <= 6.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Insulin (0.0) <= 192.50)
* DiabetesPedigreeFunction (0.55) > 0.53
* (SkinThickness (26.0) <= 32.50 AND Pregnancies (5.0) <= 6.50)
* BloodPressure (75.0) > 69.00
* SkinThickness (26.0) <= 32.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* Pregnancies (5.0) <= 6.50
* Insulin (0.0) <= 192.50
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Insulin (0.0) <= 192.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 27.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND BMI (36.0) > 26.70)
* (Insulin (0.0) <= 192.50 AND Age (60.0) > 27.50)
* (Insulin (0.0) <= 192.50 AND BMI (36.0) > 26.70)
* (BloodPressure (75.0) > 69.00 AND BMI (36.0) > 26.70)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50)
* (BloodPressure (75.0) > 69.00 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND BMI (36.0) > 26.70) [⚠️ direction uncertain]
* (BloodPressure (75.0) > 69.00 AND Age (60.0) > 27.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND Age (60.0) > 27.50) [⚠️ direction uncertain]
* (BMI (36.0) > 26.70 AND Age (60.0) > 27.50) [⚠️ direction uncertain]

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (BMI (26.0) <= 26.70 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (SkinThickness (24.0) <= 32.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Pregnancies (3.0) <= 6.50 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Pregnancies (3.0) <= 6.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50)
* (Pregnancies (3.0) <= 6.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 69.00 AND Age (25.0) <= 27.50)
* (Glucose (108.0) <= 122.50 AND BMI (26.0) <= 26.70)
* (Insulin (0.0) <= 192.50 AND Pregnancies (3.0) <= 6.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Age (25.0) <= 27.50)
* (Insulin (0.0) <= 192.50 AND Age (25.0) <= 27.50)
* (SkinThickness (24.0) <= 32.50 AND Age (25.0) <= 27.50)
* (BMI (26.0) <= 26.70 AND Age (25.0) <= 27.50)
* (Pregnancies (3.0) <= 6.50 AND BMI (26.0) <= 26.70)
* (BloodPressure (62.0) <= 69.00 AND SkinThickness (24.0) <= 32.50) [⚠️ direction uncertain]
* (BloodPressure (62.0) <= 69.00 AND BMI (26.0) <= 26.70)

Factors impacting the probability for class Diabetic negatively:
* Glucose (108.0) <= 122.50
* BMI (26.0) <= 26.70
* Pregnancies (3.0) <= 6.50
* Age (25.0) <= 27.50
* SkinThickness (24.0) <= 32.50
* Insulin (0.0) <= 192.50
* BloodPressure (62.0) <= 69.00
* DiabetesPedigreeFunction (0.22) <= 0.53 [⚠️ direction uncertain]

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [9]:
# 3. HTML - returns HTML table
html_narratives = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="html",
)
from IPython.display import HTML

HTML(html_narratives)

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [10]:
# 4. Dictionary - returns list of dictionaries
dict_narratives = explanations.to_narrative(
    expertise_level="advanced", output_format="dict"
)
dict_narratives

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

[{'instance_index': 0,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.367\nPrediction Interval: [0.348, 0.378]\n\nFactors impacting the calibrated probability for class Diabetic positively:\nGlucose (145.0) > 122.50                                                                                — weight ≈ 0.191 [0.186, 0.212]\nPregnancies (13.0) > 6.50                                                                               — weight ≈ 0.179 [0.173, 0.205]\n(BloodPressure (82.0) > 69.00 AND DiabetesPedigreeFunction (0.24) <= 0.53)                              — weight ≈ 0.043 [0.020, 0.060]\n(SkinThickness (19.0) <= 32.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                             — weight ≈ 0.031 [0.002, 0.051]\n(BMI (22.2) <= 26.70 AND DiabetesPedigreeFunction (0.24) <= 0.53)                                       — weight ≈ 0.027 [-0.014, 0.056] [⚠️ direction uncertain]\n(BloodPressure (82.0) > 69.00 AND BMI (22.2) <= 26.70)                                                  — weight ≈ 0.007 [-0.014, 0.020] [⚠️ direction uncertain]\n(Insulin (110.0) <= 192.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                                 — weight ≈ 0.005 [-0.016, 0.017] [⚠️ direction uncertain]\n(SkinThickness (19.0) <= 32.50 AND BMI (22.2) <= 26.70)                                                 — weight ≈ 0.004 [-0.016, 0.015] [⚠️ direction uncertain]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\n(BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)               — weight ≈ -0.193 [-0.213, -0.189]\n(Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)                                                — weight ≈ -0.192 [-0.212, -0.187]\n(Insulin (110.0) <= 192.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)                        — weight ≈ -0.192 [-0.212, -0.187]\n(Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)                                                      — weight ≈ -0.191 [-0.212, -0.186]\n(BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)                     — weight ≈ -0.190 [-0.212, -0.186]\n(BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)                                             — weight ≈ -0.190 [-0.212, -0.185]\n(Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)                  — weight ≈ -0.190 [-0.211, -0.185]\n(Pregnancies (13.0) > 6.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)               — weight ≈ -0.190 [-0.212, -0.185]\n(DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)    — weight ≈ -0.189 [-0.211, -0.184]\n(Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)                        — weight ≈ -0.189 [-0.212, -0.184]\n(Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)                                                — weight ≈ -0.189 [-0.212, -0.184]\n(Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                                  — weight ≈ -0.189 [-0.211, -0.184]\n(SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)              — weight ≈ -0.189 [-0.211, -0.184]\n(DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)          — weight ≈ -0.188 [-0.211, -0.183]\n(SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)                    — weight ≈ -0.188 [-0.211, -0.182]\n(DiabetesPedigreeFunction (0.24) <= 0.53 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50) — weight ≈ -0.187 [-0.211, -0.182]\n(SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50)                                            — weight ≈ -0.187 [-0.211, -0.182]\n(DiabetesPedigreeFunction (0.24) <= 0.53 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)    — weight ≈ -0.187 [-0.210, -0.182]\n(SkinThickness (19.0) <= 32.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)           — weight ≈ -0.186 [-0.210, -0.181]\n(SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)              — weight ≈ -0.185 [-0.210, -0.179]\n(Pregnancies (13.0) > 6.50 AND Insulin (110.0) <= 192.50)                                               — weight ≈ -0.185 [-0.208, -0.179]\nBMI (22.2) <= 26.70                                                                                     — weight ≈ -0.183 [-0.193, -0.176]\n(Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 26.70)                                                     — weight ≈ -0.179 [-0.205, -0.173]\n(Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)                                 — weight ≈ -0.159 [-0.184, -0.153]\n(SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50)                                           — weight ≈ -0.159 [-0.184, -0.153]\n(BloodPressure (82.0) > 69.00 AND Pregnancies (13.0) > 6.50)                                            — weight ≈ -0.139 [-0.163, -0.132]\nDiabetesPedigreeFunction (0.24) <= 0.53                                                                 — weight ≈ -0.071 [-0.133, 0.008] [⚠️ direction uncertain]\nInsulin (110.0) <= 192.50                                                                               — weight ≈ -0.050 [-0.097, 0.011] [⚠️ direction uncertain]\n(BloodPressure (82.0) > 69.00 AND Insulin (110.0) <= 192.50)                                            — weight ≈ -0.040 [-0.060, -0.030]\n(Insulin (110.0) <= 192.50 AND BMI (22.2) <= 26.70)                                                     — weight ≈ -0.040 [-0.060, -0.030]\nBloodPressure (82.0) > 69.00                                                                            — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]\nSkinThickness (19.0) <= 32.50                                                                           — weight ≈ -0.011 [-0.025, 0.011] [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 1,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.550\nPrediction Interval: [0.542, 0.559]\n\nFactors impacting the calibrated probability for class Diabetic positively:\nBMI (34.1) > 26.70                                                                            — weight ≈ 0.365 [0.359, 0.392]\n(BloodPressure (92.0) > 69.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)           — weight ≈ 0.208 [0.189, 0.263]\n(Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)                                  — weight ≈ 0.208 [0.191, 0.257]\nAge (38.0) > 27.50                                                                            — weight ≈ 0.180 [0.168, 0.200]\nSkinThickness (0.0) <= 32.50                                                                  — weight ≈ 0.172 [0.159, 0.194]\n(Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)           — weight ≈ 0.169 [0.151, 0.217]\n(Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)                                            — weight ≈ 0.142 [0.120, 0.191]\n(Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)                     — weight ≈ 0.125 [0.106, 0.170]\n(Glucose (117.0) <= 122.50 AND Age (38.0) > 27.50)                                            — weight ≈ 0.120 [0.095, 0.177]\n(SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00) — weight ≈ 0.107 [0.087, 0.150]\n(SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)           — weight ≈ 0.084 [0.063, 0.127]\n(BloodPressure (92.0) > 69.00 AND BMI (34.1) > 26.70)                                         — weight ≈ 0.073 [0.057, 0.107]\n(Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)                                  — weight ≈ 0.062 [0.040, 0.104]\n(BloodPressure (92.0) > 69.00 AND Age (38.0) > 27.50)                                         — weight ≈ 0.037 [0.015, 0.075]\n(BloodPressure (92.0) > 69.00 AND SkinThickness (0.0) <= 32.50)                               — weight ≈ 0.029 [0.015, 0.052]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\nGlucose (117.0) <= 122.50                                                                     — weight ≈ -0.133 [-0.217, -0.094]\nBloodPressure (92.0) > 69.00                                                                  — weight ≈ -0.053 [-0.086, -0.034]\n(BMI (34.1) > 26.70 AND Age (38.0) > 27.50)                                                   — weight ≈ -0.051 [-0.070, -0.035]\n(SkinThickness (0.0) <= 32.50 AND Age (38.0) > 27.50)                                         — weight ≈ -0.047 [-0.074, -0.023]\n(SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 26.70)                                         — weight ≈ -0.037 [-0.059, -0.016]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 2,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.437\nPrediction Interval: [0.356, 0.500]\n\nFactors impacting the calibrated probability for class Diabetic positively:\n(Pregnancies (5.0) <= 6.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)               — weight ≈ 0.341 [0.328, 0.387]\n(Pregnancies (5.0) <= 6.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)              — weight ≈ 0.341 [0.328, 0.387]\n(Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)                                                — weight ≈ 0.341 [0.328, 0.387]\n(Insulin (0.0) <= 192.50 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)                    — weight ≈ 0.340 [0.327, 0.387]\n(Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                         — weight ≈ 0.340 [0.327, 0.387]\n(BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                      — weight ≈ 0.338 [0.324, 0.386]\n(Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                                                       — weight ≈ 0.332 [0.315, 0.384]\n(SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                     — weight ≈ 0.332 [0.317, 0.380]\n(BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)                                             — weight ≈ 0.331 [0.314, 0.384]\n(BloodPressure (75.0) > 69.00 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)           — weight ≈ 0.330 [0.314, 0.381]\n(BMI (36.0) > 26.70 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)                         — weight ≈ 0.325 [0.308, 0.380]\n(SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)                                            — weight ≈ 0.325 [0.308, 0.376]\n(Insulin (0.0) <= 192.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)                — weight ≈ 0.316 [0.296, 0.371]\n(Insulin (0.0) <= 192.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)                 — weight ≈ 0.314 [0.296, 0.369]\n(Insulin (0.0) <= 192.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                           — weight ≈ 0.314 [0.294, 0.370]\n(BMI (36.0) > 26.70 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)                                — weight ≈ 0.308 [0.289, 0.360]\n(Glucose (109.0) <= 122.50 AND Insulin (0.0) <= 192.50)                                                  — weight ≈ 0.305 [0.284, 0.365]\n(BMI (36.0) > 26.70 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)                     — weight ≈ 0.289 [0.271, 0.338]\nBMI (36.0) > 26.70                                                                                       — weight ≈ 0.267 [0.264, 0.283]\n(BMI (36.0) > 26.70 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)                      — weight ≈ 0.266 [0.243, 0.322]\n(Glucose (109.0) <= 122.50 AND BMI (36.0) > 26.70)                                                       — weight ≈ 0.255 [0.233, 0.305]\nAge (60.0) > 27.50                                                                                       — weight ≈ 0.251 [0.245, 0.277]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)     — weight ≈ 0.165 [0.150, 0.195]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50) — weight ≈ 0.140 [0.115, 0.174]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)            — weight ≈ 0.118 [0.104, 0.138]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50)                                   — weight ≈ 0.113 [0.089, 0.142]\n(Pregnancies (5.0) <= 6.50 AND Age (60.0) > 27.50)                                                       — weight ≈ 0.113 [0.105, 0.122]\n(Pregnancies (5.0) <= 6.50 AND BMI (36.0) > 26.70)                                                       — weight ≈ 0.113 [0.105, 0.122]\n(BloodPressure (75.0) > 69.00 AND Pregnancies (5.0) <= 6.50)                                             — weight ≈ 0.111 [0.101, 0.122]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)  — weight ≈ 0.105 [0.084, 0.131]\n(Pregnancies (5.0) <= 6.50 AND Insulin (0.0) <= 192.50)                                                  — weight ≈ 0.069 [0.043, 0.091]\nDiabetesPedigreeFunction (0.55) > 0.53                                                                   — weight ≈ 0.066 [0.055, 0.086]\n(SkinThickness (26.0) <= 32.50 AND Pregnancies (5.0) <= 6.50)                                            — weight ≈ 0.064 [0.035, 0.091]\nBloodPressure (75.0) > 69.00                                                                             — weight ≈ 0.059 [0.046, 0.081]\nSkinThickness (26.0) <= 32.50                                                                            — weight ≈ 0.019 [-0.027, 0.078] [⚠️ direction uncertain]\n\nFactors impacting the calibrated probability for class Diabetic negatively:\nGlucose (109.0) <= 122.50                                                                                — weight ≈ -0.318 [-0.379, -0.297]\nPregnancies (5.0) <= 6.50                                                                                — weight ≈ -0.113 [-0.122, -0.105]\nInsulin (0.0) <= 192.50                                                                                  — weight ≈ -0.091 [-0.122, -0.063]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Insulin (0.0) <= 192.50)                                     — weight ≈ -0.068 [-0.087, -0.056]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 27.50)                                          — weight ≈ -0.057 [-0.084, -0.040]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND BMI (36.0) > 26.70)                                          — weight ≈ -0.055 [-0.083, -0.037]\n(Insulin (0.0) <= 192.50 AND Age (60.0) > 27.50)                                                         — weight ≈ -0.048 [-0.082, -0.024]\n(Insulin (0.0) <= 192.50 AND BMI (36.0) > 26.70)                                                         — weight ≈ -0.047 [-0.081, -0.023]\n(BloodPressure (75.0) > 69.00 AND BMI (36.0) > 26.70)                                                    — weight ≈ -0.046 [-0.080, -0.021]\n(DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50)                                   — weight ≈ -0.043 [-0.083, -0.014]\n(BloodPressure (75.0) > 69.00 AND Insulin (0.0) <= 192.50)                                               — weight ≈ -0.034 [-0.081, 0.001] [⚠️ direction uncertain]\n(SkinThickness (26.0) <= 32.50 AND Insulin (0.0) <= 192.50)                                              — weight ≈ -0.033 [-0.081, 0.003] [⚠️ direction uncertain]\n(SkinThickness (26.0) <= 32.50 AND BMI (36.0) > 26.70)                                                   — weight ≈ -0.022 [-0.064, 0.009] [⚠️ direction uncertain]\n(BloodPressure (75.0) > 69.00 AND Age (60.0) > 27.50)                                                    — weight ≈ -0.020 [-0.050, 0.002] [⚠️ direction uncertain]\n(SkinThickness (26.0) <= 32.50 AND Age (60.0) > 27.50)                                                   — weight ≈ -0.020 [-0.060, 0.009] [⚠️ direction uncertain]\n(BMI (36.0) > 26.70 AND Age (60.0) > 27.50)                                                              — weight ≈ -0.014 [-0.050, 0.014] [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 3,

In [11]:
# Different expertise levels:

# Single level
beginner_only = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(beginner_only)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.367

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 122.50
* Pregnancies (13.0) > 6.50
* (BloodPressure (82.0) > 69.00 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (BMI (22.2) <= 26.70 AND DiabetesPedigreeFunction (0.24) <= 0.53) [⚠️ direction uncertain]
* (BloodPressure (82.0) > 69.00 AND BMI (22.2) <= 26.70) [⚠️ direction uncertain]
* (Insulin (110.0) <= 192.50 AND DiabetesPedigreeFunction (0.24) <= 0.53) [⚠️ direction uncertain]
* (SkinThickness (19.0) <= 32.50 AND BMI (22.2) <= 26.70) [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Insulin (110.0) <= 192.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Pregnancies (13.0) > 6.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Glucose (145.0) > 122.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND Insulin (110.0) <= 192.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50 AND BMI (22.2) <= 26.70)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Glucose (145.0) > 122.50)
* (DiabetesPedigreeFunction (0.24) <= 0.53 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND BloodPressure (82.0) > 69.00 AND Glucose (145.0) > 122.50)
* (SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50 AND Glucose (145.0) > 122.50)
* (Pregnancies (13.0) > 6.50 AND Insulin (110.0) <= 192.50)
* BMI (22.2) <= 26.70
* (Pregnancies (13.0) > 6.50 AND BMI (22.2) <= 26.70)
* (Pregnancies (13.0) > 6.50 AND DiabetesPedigreeFunction (0.24) <= 0.53)
* (SkinThickness (19.0) <= 32.50 AND Pregnancies (13.0) > 6.50)
* (BloodPressure (82.0) > 69.00 AND Pregnancies (13.0) > 6.50)
* DiabetesPedigreeFunction (0.24) <= 0.53 [⚠️ direction uncertain]
* Insulin (110.0) <= 192.50 [⚠️ direction uncertain]
* (BloodPressure (82.0) > 69.00 AND Insulin (110.0) <= 192.50)
* (Insulin (110.0) <= 192.50 AND BMI (22.2) <= 26.70)
* BloodPressure (82.0) > 69.00 [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50 [⚠️ direction uncertain]

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 26.70
* (BloodPressure (92.0) > 69.00 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* Age (38.0) > 27.50
* SkinThickness (0.0) <= 32.50
* (Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* (Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Age (38.0) > 27.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BloodPressure (92.0) > 69.00)
* (SkinThickness (0.0) <= 32.50 AND Glucose (117.0) <= 122.50 AND BMI (34.1) > 26.70)
* (BloodPressure (92.0) > 69.00 AND BMI (34.1) > 26.70)
* (Glucose (117.0) <= 122.50 AND SkinThickness (0.0) <= 32.50)
* (BloodPressure (92.0) > 69.00 AND Age (38.0) > 27.50)
* (BloodPressure (92.0) > 69.00 AND SkinThickness (0.0) <= 32.50)

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 122.50
* BloodPressure (92.0) > 69.00
* (BMI (34.1) > 26.70 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND Age (38.0) > 27.50)
* (SkinThickness (0.0) <= 32.50 AND BMI (34.1) > 26.70)

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.437

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (5.0) <= 6.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (BloodPressure (75.0) > 69.00 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (BMI (36.0) > 26.70 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (BMI (36.0) > 26.70 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (Glucose (109.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (BMI (36.0) > 26.70 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* BMI (36.0) > 26.70
* (BMI (36.0) > 26.70 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Glucose (109.0) <= 122.50 AND BMI (36.0) > 26.70)
* Age (60.0) > 27.50
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50 AND Glucose (109.0) <= 122.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND SkinThickness (26.0) <= 32.50 AND Glucose (109.0) <= 122.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50 AND Age (60.0) > 27.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Age (60.0) > 27.50)
* (Pregnancies (5.0) <= 6.50 AND BMI (36.0) > 26.70)
* (BloodPressure (75.0) > 69.00 AND Pregnancies (5.0) <= 6.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND BloodPressure (75.0) > 69.00 AND Glucose (109.0) <= 122.50)
* (Pregnancies (5.0) <= 6.50 AND Insulin (0.0) <= 192.50)
* DiabetesPedigreeFunction (0.55) > 0.53
* (SkinThickness (26.0) <= 32.50 AND Pregnancies (5.0) <= 6.50)
* BloodPressure (75.0) > 69.00
* SkinThickness (26.0) <= 32.50 [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 122.50
* Pregnancies (5.0) <= 6.50
* Insulin (0.0) <= 192.50
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Insulin (0.0) <= 192.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Age (60.0) > 27.50)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND BMI (36.0) > 26.70)
* (Insulin (0.0) <= 192.50 AND Age (60.0) > 27.50)
* (Insulin (0.0) <= 192.50 AND BMI (36.0) > 26.70)
* (BloodPressure (75.0) > 69.00 AND BMI (36.0) > 26.70)
* (DiabetesPedigreeFunction (0.55) > 0.53 AND Pregnancies (5.0) <= 6.50)
* (BloodPressure (75.0) > 69.00 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND BMI (36.0) > 26.70) [⚠️ direction uncertain]
* (BloodPressure (75.0) > 69.00 AND Age (60.0) > 27.50) [⚠️ direction uncertain]
* (SkinThickness (26.0) <= 32.50 AND Age (60.0) > 27.50) [⚠️ direction uncertain]
* (BMI (36.0) > 26.70 AND Age (60.0) > 27.50) [⚠️ direction uncertain]

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.062

Factors impacting the probability for class Diabetic positively:
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (BMI (26.0) <= 26.70 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (SkinThickness (24.0) <= 32.50 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (Pregnancies (3.0) <= 6.50 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Pregnancies (3.0) <= 6.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (SkinThickness (24.0) <= 32.50 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND BloodPressure (62.0) <= 69.00 AND Glucose (108.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Glucose (108.0) <= 122.50 AND SkinThickness (24.0) <= 32.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Glucose (108.0) <= 122.50)
* (BMI (26.0) <= 26.70 AND Insulin (0.0) <= 192.50 AND Glucose (108.0) <= 122.50)
* (Pregnancies (3.0) <= 6.50 AND Age (25.0) <= 27.50)
* (BloodPressure (62.0) <= 69.00 AND Pregnancies (3.0) <= 6.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Pregnancies (3.0) <= 6.50)
* (Pregnancies (3.0) <= 6.50 AND SkinThickness (24.0) <= 32.50)
* (BloodPressure (62.0) <= 69.00 AND Age (25.0) <= 27.50)
* (Glucose (108.0) <= 122.50 AND BMI (26.0) <= 26.70)
* (Insulin (0.0) <= 192.50 AND Pregnancies (3.0) <= 6.50)
* (DiabetesPedigreeFunction (0.22) <= 0.53 AND Age (25.0) <= 27.50)
* (Insulin (0.0) <= 192.50 AND Age (25.0) <= 27.50)
* (SkinThickness (24.0) <= 32.50 AND Age (25.0) <= 27.50)
* (BMI (26.0) <= 26.70 AND Age (25.0) <= 27.50)
* (Pregnancies (3.0) <= 6.50 AND BMI (26.0) <= 26.70)
* (BloodPressure (62.0) <= 69.00 AND SkinThickness (24.0) <= 32.50) [⚠️ direction uncertain]
* (BloodPressure (62.0) <= 69.00 AND BMI (26.0) <= 26.70)

Factors impacting the probability for class Diabetic negatively:
* Glucose (108.0) <= 122.50
* BMI (26.0) <= 26.70
* Pregnancies (3.0) <= 6.50
* Age (25.0) <= 27.50
* SkinThickness (24.0) <= 32.50
* Insulin (0.0) <= 192.50
* BloodPressure (62.0) <= 69.00
* DiabetesPedigreeFunction (0.22) <= 0.53 [⚠️ direction uncertain]

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 26.70
* Glucose (137.0) > 122.50
* (BloodPressure (90.0) > 69.00 AND SkinThickness (41.0) > 32.50)
* (SkinThickness (41.0) > 32.50 AND Age (39.0) > 27.50)
* (SkinThickness (41.0) > 32.50 AND BMI (32.0) > 26.70)
* (BloodPressure (90.0) > 69.00 AND Age (39.0) > 27.50)
* Age (39.0) > 27.50
* (BMI (32.0) > 26.70 AND Age (39.0) > 27.50) [⚠️ direction uncertain]
* (BloodPressure (90.0) > 69.00 AND BMI (32.0) > 26.70) [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* (BMI (32.0) > 26.70 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BloodPressure (90.0) > 69.00 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (SkinThickness (41.0) > 32.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BloodPressure (90.0) > 69.00 AND Glucose (137.0) > 122.50 AND BMI (32.0) > 26.70)
* (Glucose (137.0) > 122.50 AND BMI (32.0) > 26.70)
* (SkinThickness (41.0) > 32.50 AND Glucose (137.0) > 122.50 AND BMI (32.0) > 26.70)
* (Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50)
* (Age (39.0) > 27.50 AND Glucose (137.0) > 122.50 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* (BloodPressure (90.0) > 69.00 AND Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50)
* (BloodPressure (90.0) > 69.00 AND Glucose (137.0) > 122.50)
* (Age (39.0) > 27.50 AND Glucose (137.0) > 122.50 AND BMI (32.0) > 26.70)
* (Age (39.0) > 27.50 AND Glucose (137.0) > 122.50 AND SkinThickness (41.0) > 32.50)
* (Age (39.0) > 27.50 AND BloodPressure (90.0) > 69.00 AND Glucose (137.0) > 122.50)
* (Glucose (137.0) > 122.50 AND Age (39.0) > 27.50)
* SkinThickness (41.0) > 32.50
* DiabetesPedigreeFunction (0.39) <= 0.53
* (BMI (32.0) > 26.70 AND DiabetesPedigreeFunction (0.39) <= 0.53)
* BloodPressure (90.0) > 69.00 [⚠️ direction uncertain]
* (SkinThickness (41.0) > 32.50 AND DiabetesPedigreeFunction (0.39) <= 0.53) [⚠️ direction uncertain]
* (DiabetesPedigreeFunction (0.39) <= 0.53 AND Age (39.0) > 27.50) [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.378

Factors impacting the probability for class Diabetic positively:
* (BloodPressure (0.0) <= 69.00 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 26.70)
* (BloodPressure (0.0) <= 69.00 AND Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (Glucose (100.0) <= 122.50 AND BMI (30.0) > 26.70)
* (BMI (30.0) > 26.70 AND Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (Glucose (100.0) <= 122.50 AND BloodPressure (0.0) <= 69.00)
* (Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (Insulin (0.0) <= 192.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 26.70)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 26.70)
* (Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (BloodPressure (0.0) <= 69.00 AND Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (Insulin (0.0) <= 192.50 AND Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND BMI (30.0) > 26.70)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (Pregnancies (7.0) > 6.50 AND Age (32.0) > 27.50 AND Glucose (100.0) <= 122.50)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND BloodPressure (0.0) <= 69.00)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Glucose (100.0) <= 122.50 AND Insulin (0.0) <= 192.50)
* (Pregnancies (7.0) > 6.50 AND Glucose (100.0) <= 122.50 AND BloodPressure (0.0) <= 69.00)
* BMI (30.0) > 26.70
* Pregnancies (7.0) > 6.50
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BloodPressure (0.0) <= 69.00)
* (BloodPressure (0.0) <= 69.00 AND BMI (30.0) > 26.70)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND BMI (30.0) > 26.70)
* (Age (32.0) > 27.50 AND BloodPressure (0.0) <= 69.00) [⚠️ direction uncertain]
* (BloodPressure (0.0) <= 69.00 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* Age (32.0) > 27.50
* (Age (32.0) > 27.50 AND Insulin (0.0) <= 192.50) [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.48) <= 0.53 [⚠️ direction uncertain]
* (Age (32.0) > 27.50 AND BMI (30.0) > 26.70) [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 122.50
* (Pregnancies (7.0) > 6.50 AND Insulin (0.0) <= 192.50)
* (Pregnancies (7.0) > 6.50 AND BMI (30.0) > 26.70)
* (DiabetesPedigreeFunction (0.48) <= 0.53 AND Pregnancies (7.0) > 6.50)
* Insulin (0.0) <= 192.50 [⚠️ direction uncertain]
* (Age (32.0) > 27.50 AND Pregnancies (7.0) > 6.50)
* BloodPressure (0.0) <= 69.00 [⚠️ direction uncertain]
* (Pregnancies (7.0) > 6.50 AND BloodPressure (0.0) <= 69.00) [⚠️ direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.550

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 122.50
* Age (51.0) > 27.50
* DiabetesPedigreeFunction (0.59) > 0.53
* BloodPressure (72.0) > 69.00

Factors impacting the probability for class Diabetic negatively:
* (DiabetesPedigreeFunction (0.59) > 0.53 AND Glucose (166.0) > 122.50 AND Age (51.0) > 27.50)
* (BMI (25.8) <= 26.70 AND Glucose (166.0) > 122.50 AND DiabetesPedigreeFunction (0.59) > 0.53)
* (Glucose (166.0) > 122.50 AND DiabetesPedigreeFunction (0.59) > 0.53)
* (BMI (25.8) <= 26.70 AND Glucose (166.0) > 122.50 AND Age (51.0) > 27.50)
* (Glucose (166.0) > 122.50 AND Age (51.0) > 27.50)
* (Glucose (166.0) > 122.50 AND BMI (25.8) <= 26.70)
* (BloodPressure (72.0) > 69.00 AND Glucose (166.0) > 122.50 AND DiabetesPedigreeFunction (0.59) > 0.53)
* (BloodPressure (72.0) > 69.00 AND Glucose (166.0) > 122.50 AND BMI (25.8) <= 26.70)
* (BloodPressure (72.0) > 69.00 AND Glucose (166.0) > 122.50 AND Age (51.0) > 27.50)
* (Glucose (166.0) > 122.50 AND BloodPressure (72.0) > 69.00)
* BMI (25.8) <= 26.70
* (BMI (25.8) <= 26.70 AND DiabetesPedigreeFunction (0.59) > 0.53)

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [12]:
# Multiple levels
all_levels = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="dataframe",
)
all_levels

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_intermediate,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification

In [13]:
# Template path handling:

# If exp.yaml doesn't exist, automatically falls back to explain_template.yaml
narratives = explanations.to_narrative(
    template_path="exp.yaml",  # Will use default if not found
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)
narratives

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification

In [14]:
# Use custom template
narratives = explanations.to_narrative(
    template_path="/path/to/custom_template.yaml",
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)

# Use default template
narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="dataframe"
)

print("The to_narrative method provides a clean, intuitive API for generating narratives!")

c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(
c:\Users\loftuw\Documents\Github\moffran-calibrated_explanations\calibrated_explanations\venv-wheel\Lib\site-packages\calibrated_explanations\explanations\explanations.py:1507: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

The to_narrative method provides a clean, intuitive API for generating narratives!