In [36]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [37]:
import sys
import os
from pathlib import Path
# sys.path.insert(0, "/Users/poorna/Downloads/CE-updated/calibrated_explanations/src")

# Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from calibrated_explanations import CalibratedExplainer, __version__

print(f"calibrated_explanations {__version__}")

calibrated_explanations v0.11.0-dev

In [38]:
# Load and preprocess the data
num_to_test = 10  # number of instances to test, one from each class
dataset = "diabetes_full"
delimiter = ","
model = "RF"

filename = "../data/diabetes_full.csv"
df = pd.read_csv(filename, delimiter=delimiter)
target = "Y"
X, y = df.drop(target, axis=1), df[target]
no_of_classes = len(np.unique(y))
no_of_features = X.shape[1]
no_of_instances = X.shape[0]

# find categorical features
categorical_features = [i for i in range(no_of_features) if len(np.unique(X.iloc[:, i])) < 10]

# select test instances from each class and split into train, cal and test
idx = np.argsort(y.values).astype(int)
X, y = X.values[idx, :], y.values[idx]
test_index = np.array(
    [
        *range(int(num_to_test / 2)),
        *range(no_of_instances - 1, no_of_instances - int(num_to_test / 2) - 1, -1),
    ]
)
train_index = np.setdiff1d(np.array(range(no_of_instances)), test_index)
x_train, x_test = X[train_index, :], X[test_index, :]
y_train, y_test = y[train_index], y[test_index]
X_prop_train, x_cal, y_prop_train, y_cal = train_test_split(
    x_train, y_train, test_size=0.33, random_state=42, stratify=y_train
)

In [39]:
# Train the model and create the explainer
model = RandomForestClassifier()

model.fit(X_prop_train, y_prop_train)

ce = CalibratedExplainer(
    model,
    x_cal,
    y_cal,
    feature_names=df.columns,
    categorical_features=categorical_features,
    class_labels={0: "Non-diabetic", 1: "Diabetic"},
)

C:\Users\loftuw\CUDATemp\ipykernel_49240\2927877249.py:6: UserWarning: condition_source not provided; defaulting to 'prediction' in v0.10.3. Pass condition_source='observed' to retain previous behaviour.
  ce = CalibratedExplainer(

In [40]:
factual_explanations = ce.explain_factual(x_test)
print("Probability [lower and upper bound] for Diabetic:")
print(
    *zip(
        [
            f"Instance {i}: {exp.prediction['predict']:.3f} [{exp.prediction['low']:5.3f}, {exp.prediction['high']:5.3f}]"
            for i, exp in enumerate(factual_explanations)
        ]
    ),
    sep="\n",
)

Probability [lower and upper bound] for Diabetic:
('Instance 0: 0.395 [0.368, 0.412]',)
('Instance 1: 0.467 [0.429, 0.500]',)
('Instance 2: 0.467 [0.429, 0.500]',)
('Instance 3: 0.057 [0.025, 0.059]',)
('Instance 4: 0.600 [0.556, 0.667]',)
('Instance 5: 0.360 [0.342, 0.370]',)
('Instance 6: 0.415 [0.382, 0.438]',)
('Instance 7: 0.682 [0.667, 0.714]',)
('Instance 8: 0.750 [0.733, 0.800]',)
('Instance 9: 0.250 [0.143, 0.286]',)

Example demonstrating the new to_narrative API.

This shows the clean API for generating narratives from calibrated explanations.

In [41]:
# The new to_narrative method provides a clean API:
explanations = factual_explanations

# Basic usage
narratives = explanations[0].to_narrative(
    expertise_level=("beginner", "advanced"),
    output_format="text",
)
print(narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Advanced):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.395
Prediction Interval: [0.368, 0.412]

Factors increasing Calibrated Probability:
Glucose (145.0) > 139.50 — weight ≈ 0.195 [0.180, 0.252],
Pregnancies (13.0) > 6.50 — weight ≈ 0.050 [0.030, 0.089],
Age (57.0) > 28.50 — weight ≈ 0.023 [0.010, 0.044],

Factors decreasing Calibrated Probability:
BMI (22.2) <= 28.05 — weight ≈ -0.172 [-0.214, -0.141],
Insulin (110.0) <= 192.50 — weight ≈ -0.013 [-0.034, 0.017], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.24) <= 0.56 — weight ≈ -0.013 [-0.034, 0.017], [⚠️ direction uncertain]
BloodPressure (82.0) > 63.00 — weight ≈ -0.007 [-0.026, 0.022], [⚠️ direction uncertain]
SkinThickness (19.0) <= 32.50 — weight ≈ -0.006 [-0.026, 0.022], [⚠️ direction uncertain]

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.395

Factors increasing Calibrated Probability:
* Glucose (145.0) > 139.50,
* Pregnancies (13.0) > 6.50,
* Age (57.0) > 28.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 28.05,
* Insulin (110.0) <= 192.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.24) <= 0.56, [⚠️ direction uncertain]
* BloodPressure (82.0) > 63.00, [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50, [⚠️ direction uncertain]

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanation.py:512: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  result = plugin.plot(

In [44]:
# Different output formats:

# 1. DataFrame (default) - returns pandas DataFrame
df_narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="markdown"
)
print(df_narratives)

## Instance 0

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.395
Prediction Interval: [0.368, 0.412]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (145.0) > 139.50 — weight ≈ 0.195 [0.180, 0.252],
Pregnancies (13.0) > 6.50 — weight ≈ 0.050 [0.030, 0.089],
Age (57.0) > 28.50 — weight ≈ 0.023 [0.010, 0.044],

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (22.2) <= 28.05 — weight ≈ -0.172 [-0.214, -0.141],
Insulin (110.0) <= 192.50 — weight ≈ -0.013 [-0.034, 0.017], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.24) <= 0.56 — weight ≈ -0.013 [-0.034, 0.017], [⚠️ direction uncertain]
BloodPressure (82.0) > 63.00 — weight ≈ -0.007 [-0.026, 0.022], [⚠️ direction uncertain]
SkinThickness (19.0) <= 32.50 — weight ≈ -0.006 [-0.026, 0.022], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.395

Factors impacting the probability for class Diabetic positively:
* Glucose (145.0) > 139.50,
* Pregnancies (13.0) > 6.50,
* Age (57.0) > 28.50,

Factors impacting the probability for class Diabetic negatively:
* BMI (22.2) <= 28.05,
* Insulin (110.0) <= 192.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.24) <= 0.56, [⚠️ direction uncertain]
* BloodPressure (82.0) > 63.00, [⚠️ direction uncertain]
* SkinThickness (19.0) <= 32.50, [⚠️ direction uncertain]
```

## Instance 1

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.467
Prediction Interval: [0.429, 0.500]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (34.1) > 28.05 — weight ≈ 0.267 [0.261, 0.293],
SkinThickness (0.0) <= 32.50 — weight ≈ 0.083 [0.069, 0.107],
Age (38.0) > 28.50 — weight ≈ 0.065 [0.046, 0.094],
BloodPressure (92.0) > 63.00 — weight ≈ 0.052 [0.029, 0.084],
Insulin (0.0) <= 192.50 — weight ≈ 0.017 [-0.013, 0.054], [⚠️ direction uncertain]
Pregnancies (5.0) <= 6.50 — weight ≈ 0.000 [-0.033, 0.038], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (117.0) <= 139.50 — weight ≈ -0.160 [-0.216, -0.124],
DiabetesPedigreeFunction (0.34) <= 0.56 — weight ≈ -0.070 [-0.112, -0.032],
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.467

Factors impacting the probability for class Diabetic positively:
* BMI (34.1) > 28.05,
* SkinThickness (0.0) <= 32.50,
* Age (38.0) > 28.50,
* BloodPressure (92.0) > 63.00,
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* Pregnancies (5.0) <= 6.50, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (117.0) <= 139.50,
* DiabetesPedigreeFunction (0.34) <= 0.56,
```

## Instance 2

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.467
Prediction Interval: [0.429, 0.500]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (36.0) > 28.05 — weight ≈ 0.324 [0.317, 0.362],
Age (60.0) > 28.50 — weight ≈ 0.267 [0.252, 0.324],
BloodPressure (75.0) > 63.00 — weight ≈ 0.052 [0.029, 0.084],
SkinThickness (26.0) <= 32.50 — weight ≈ 0.052 [0.029, 0.084],
Pregnancies (5.0) <= 6.50 — weight ≈ 0.000 [-0.033, 0.038], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (109.0) <= 139.50 — weight ≈ -0.262 [-0.333, -0.235],
Insulin (0.0) <= 192.50 — weight ≈ -0.083 [-0.112, -0.060],
DiabetesPedigreeFunction (0.55) <= 0.56 — weight ≈ -0.028 [-0.060, 0.006], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.467

Factors impacting the probability for class Diabetic positively:
* BMI (36.0) > 28.05,
* Age (60.0) > 28.50,
* BloodPressure (75.0) > 63.00,
* SkinThickness (26.0) <= 32.50,
* Pregnancies (5.0) <= 6.50, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (109.0) <= 139.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.55) <= 0.56, [⚠️ direction uncertain]
```

## Instance 3

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.057
Prediction Interval: [0.025, 0.059]

Factors impacting the calibrated probability for class Diabetic positively:
Insulin (0.0) <= 192.50 — weight ≈ 0.008 [0.007, 0.032],

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (108.0) <= 139.50 — weight ≈ -0.280 [-0.300, -0.235],
Pregnancies (3.0) <= 6.50 — weight ≈ -0.148 [-0.167, -0.089],
SkinThickness (24.0) <= 32.50 — weight ≈ -0.138 [-0.153, -0.080],
Age (25.0) <= 28.50 — weight ≈ -0.117 [-0.128, -0.070],
BMI (26.0) <= 28.05 — weight ≈ -0.064 [-0.068, -0.037],
BloodPressure (62.0) <= 63.00 — weight ≈ -0.032 [-0.038, 0.032], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.22) <= 0.56 — weight ≈ -0.007 [-0.011, 0.032], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.057

Factors impacting the probability for class Diabetic positively:
* Insulin (0.0) <= 192.50,

Factors impacting the probability for class Diabetic negatively:
* Glucose (108.0) <= 139.50,
* Pregnancies (3.0) <= 6.50,
* SkinThickness (24.0) <= 32.50,
* Age (25.0) <= 28.50,
* BMI (26.0) <= 28.05,
* BloodPressure (62.0) <= 63.00, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.56, [⚠️ direction uncertain]
```

## Instance 4

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.600
Prediction Interval: [0.556, 0.667]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (32.0) > 28.05 — weight ≈ 0.222 [0.207, 0.244],
Age (39.0) > 28.50 — weight ≈ 0.185 [0.162, 0.218],
Pregnancies (7.0) > 6.50 — weight ≈ 0.064 [0.024, 0.101],
Insulin (0.0) <= 192.50 — weight ≈ 0.017 [-0.037, 0.054], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
SkinThickness (41.0) > 32.50 — weight ≈ -0.093 [-0.143, -0.072],
DiabetesPedigreeFunction (0.39) <= 0.56 — weight ≈ -0.082 [-0.114, -0.067],
Glucose (137.0) <= 139.50 — weight ≈ -0.044 [-0.127, 0.002], [⚠️ direction uncertain]
BloodPressure (90.0) > 63.00 — weight ≈ -0.027 [-0.083, 0.007], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.600

Factors impacting the probability for class Diabetic positively:
* BMI (32.0) > 28.05,
* Age (39.0) > 28.50,
* Pregnancies (7.0) > 6.50,
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* SkinThickness (41.0) > 32.50,
* DiabetesPedigreeFunction (0.39) <= 0.56,
* Glucose (137.0) <= 139.50, [⚠️ direction uncertain]
* BloodPressure (90.0) > 63.00, [⚠️ direction uncertain]
```

## Instance 5

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.360
Prediction Interval: [0.342, 0.370]

Factors impacting the calibrated probability for class Diabetic positively:
BMI (30.0) > 28.05 — weight ≈ 0.181 [0.166, 0.231],
Pregnancies (7.0) > 6.50 — weight ≈ 0.129 [0.106, 0.198],
Age (32.0) > 28.50 — weight ≈ 0.015 [-0.004, 0.055], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Glucose (100.0) <= 139.50 — weight ≈ -0.300 [-0.354, -0.269],
Insulin (0.0) <= 192.50 — weight ≈ -0.054 [-0.077, -0.022],
DiabetesPedigreeFunction (0.48) <= 0.56 — weight ≈ -0.030 [-0.046, -0.004],
BloodPressure (0.0) <= 63.00 — weight ≈ -0.023 [-0.038, 0.001], [⚠️ direction uncertain]
SkinThickness (0.0) <= 32.50 — weight ≈ -0.023 [-0.038, 0.001], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.360

Factors impacting the probability for class Diabetic positively:
* BMI (30.0) > 28.05,
* Pregnancies (7.0) > 6.50,
* Age (32.0) > 28.50, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Glucose (100.0) <= 139.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.48) <= 0.56,
* BloodPressure (0.0) <= 63.00, [⚠️ direction uncertain]
* SkinThickness (0.0) <= 32.50, [⚠️ direction uncertain]
```

## Instance 6

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.415
Prediction Interval: [0.382, 0.438]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (166.0) > 139.50 — weight ≈ 0.058 [0.046, 0.081],
Age (51.0) > 28.50 — weight ≈ 0.043 [0.030, 0.064],
BloodPressure (72.0) > 63.00 — weight ≈ 0.014 [-0.006, 0.042], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.59) > 0.56 — weight ≈ 0.013 [-0.006, 0.042], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (25.8) <= 28.05 — weight ≈ -0.257 [-0.328, -0.220],
Pregnancies (5.0) <= 6.50 — weight ≈ -0.135 [-0.164, -0.112],
SkinThickness (19.0) <= 32.50 — weight ≈ -0.090 [-0.155, -0.027],
Insulin (175.0) <= 192.50 — weight ≈ -0.035 [-0.065, 0.001], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.415

Factors impacting the probability for class Diabetic positively:
* Glucose (166.0) > 139.50,
* Age (51.0) > 28.50,
* BloodPressure (72.0) > 63.00, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.59) > 0.56, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* BMI (25.8) <= 28.05,
* Pregnancies (5.0) <= 6.50,
* SkinThickness (19.0) <= 32.50,
* Insulin (175.0) <= 192.50, [⚠️ direction uncertain]
```

## Instance 7

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.682
Prediction Interval: [0.667, 0.714]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (189.0) > 139.50 — weight ≈ 0.303 [0.289, 0.326],
Age (59.0) > 28.50 — weight ≈ 0.218 [0.176, 0.263],
BMI (30.1) > 28.05 — weight ≈ 0.162 [0.110, 0.212],
Insulin (846.0) > 192.50 — weight ≈ 0.156 [0.110, 0.200],

Factors impacting the calibrated probability for class Diabetic negatively:
Pregnancies (1.0) <= 6.50 — weight ≈ -0.061 [-0.118, -0.041],
SkinThickness (23.0) <= 32.50 — weight ≈ -0.025 [-0.090, 0.000], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.4) <= 0.56 — weight ≈ -0.018 [-0.061, -0.001],
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.682

Factors impacting the probability for class Diabetic positively:
* Glucose (189.0) > 139.50,
* Age (59.0) > 28.50,
* BMI (30.1) > 28.05,
* Insulin (846.0) > 192.50,

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (1.0) <= 6.50,
* SkinThickness (23.0) <= 32.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.4) <= 0.56,
```

## Instance 8

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.750
Prediction Interval: [0.733, 0.800]

Factors impacting the calibrated probability for class Diabetic positively:
Glucose (168.0) > 139.50 — weight ≈ 0.280 [0.253, 0.309],
BMI (38.0) > 28.05 — weight ≈ 0.068 [0.036, 0.083],
SkinThickness (0.0) <= 32.50 — weight ≈ 0.017 [-0.050, 0.042], [⚠️ direction uncertain]
Age (34.0) > 28.50 — weight ≈ 0.001 [-0.050, 0.019], [⚠️ direction uncertain]

Factors impacting the calibrated probability for class Diabetic negatively:
Pregnancies (10.0) > 6.50 — weight ≈ -0.017 [-0.117, 0.010], [⚠️ direction uncertain]
BloodPressure (74.0) > 63.00 — weight ≈ -0.017 [-0.117, 0.011], [⚠️ direction uncertain]
Insulin (0.0) <= 192.50 — weight ≈ -0.013 [-0.117, 0.017], [⚠️ direction uncertain]
DiabetesPedigreeFunction (0.54) <= 0.56 — weight ≈ -0.013 [-0.117, 0.017], [⚠️ direction uncertain]
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.750

Factors impacting the probability for class Diabetic positively:
* Glucose (168.0) > 139.50,
* BMI (38.0) > 28.05,
* SkinThickness (0.0) <= 32.50, [⚠️ direction uncertain]
* Age (34.0) > 28.50, [⚠️ direction uncertain]

Factors impacting the probability for class Diabetic negatively:
* Pregnancies (10.0) > 6.50, [⚠️ direction uncertain]
* BloodPressure (74.0) > 63.00, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.54) <= 0.56, [⚠️ direction uncertain]
```

## Instance 9

### Factual Explanation (Advanced)

```
Prediction: Diabetic
Calibrated Probability: 0.250
Prediction Interval: [0.143, 0.286]

Factors impacting the calibrated probability for class Diabetic positively:
Pregnancies (8.0) > 6.50 — weight ≈ 0.086 [0.075, 0.135],

Factors impacting the calibrated probability for class Diabetic negatively:
BMI (0.0) <= 28.05 — weight ≈ -0.175 [-0.200, -0.143],
Glucose (125.0) <= 139.50 — weight ≈ -0.140 [-0.157, -0.114],
Age (54.0) > 28.50 — weight ≈ -0.110 [-0.120, -0.092],
BloodPressure (96.0) > 63.00 — weight ≈ -0.106 [-0.118, -0.083],
DiabetesPedigreeFunction (0.23) <= 0.56 — weight ≈ -0.106 [-0.118, -0.083],
Insulin (0.0) <= 192.50 — weight ≈ -0.095 [-0.115, -0.056],
SkinThickness (0.0) <= 32.50 — weight ≈ -0.083 [-0.110, -0.028],
```

### Factual Explanation (Beginner)

```
Prediction: Diabetic
Calibrated Probability: 0.250

Factors impacting the probability for class Diabetic positively:
* Pregnancies (8.0) > 6.50,

Factors impacting the probability for class Diabetic negatively:
* BMI (0.0) <= 28.05,
* Glucose (125.0) <= 139.50,
* Age (54.0) > 28.50,
* BloodPressure (96.0) > 63.00,
* DiabetesPedigreeFunction (0.23) <= 0.56,
* Insulin (0.0) <= 192.50,
* SkinThickness (0.0) <= 32.50,
```

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1274: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  output=output_format,

In [22]:
# 2. Text - returns formatted text string
text_narratives = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(text_narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* Glucose (145.0) > 127.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 28.05,
* Insulin (110.0) <= 192.50,
* DiabetesPedigreeFunction (0.24) <= 0.57,
* BloodPressure (82.0) > 74.50,

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* BMI (34.1) > 28.05,
* SkinThickness (0.0) <= 41.50,
* Age (38.0) > 28.50,

Factors decreasing Calibrated Probability:
* Glucose (117.0) <= 127.50,
* DiabetesPedigreeFunction (0.34) <= 0.57,
* BloodPressure (92.0) > 74.50, [⚠️ direction uncertain]

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* Age (60.0) > 28.50,
* BMI (36.0) > 28.05,

Factors decreasing Calibrated Probability:
* Glucose (109.0) <= 127.50,

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.053

Factors increasing Calibrated Probability:
* Glucose (108.0) <= 127.50,
* BMI (26.0) <= 28.05,
* Age (25.0) <= 28.50,
* SkinThickness (24.0) <= 41.50,
* Pregnancies (3.0) <= 6.50,
* BloodPressure (62.0) <= 74.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.57, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* BMI (32.0) > 28.05,
* Glucose (137.0) > 127.50,
* Pregnancies (7.0) > 6.50,
* Age (39.0) > 28.50,

Factors decreasing Calibrated Probability:
* DiabetesPedigreeFunction (0.39) <= 0.57,
* BloodPressure (90.0) > 74.50, [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* BMI (30.0) > 28.05,

Factors decreasing Calibrated Probability:
* Glucose (100.0) <= 127.50,
* BloodPressure (0.0) <= 74.50,
* SkinThickness (0.0) <= 41.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.48) <= 0.57,

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* Glucose (166.0) > 127.50,
* Age (51.0) > 28.50,

Factors decreasing Calibrated Probability:
* BMI (25.8) <= 28.05,
* Pregnancies (5.0) <= 6.50, [⚠️ direction uncertain]

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.520

Factors increasing Calibrated Probability:
* Glucose (189.0) > 127.50,
* Age (59.0) > 28.50,
* BMI (30.1) > 28.05,
* Insulin (846.0) > 192.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (1.0) <= 6.50,

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.882

Factors increasing Calibrated Probability:
* Glucose (168.0) > 127.50,
* BMI (38.0) > 28.05,
* Age (34.0) > 28.50, [⚠️ direction uncertain]
* SkinThickness (0.0) <= 41.50, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (10.0) > 6.50, [⚠️ direction uncertain]

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* Pregnancies (8.0) > 6.50,

Factors decreasing Calibrated Probability:
* BMI (0.0) <= 28.05,
* Age (54.0) > 28.50,
* Glucose (125.0) <= 127.50,
* BloodPressure (96.0) > 74.50,

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [23]:
# 3. HTML - returns HTML table
html_narratives = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="html",
)
from IPython.display import HTML

HTML(html_narratives)

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [24]:
# 4. Dictionary - returns list of dictionaries
dict_narratives = explanations.to_narrative(
    expertise_level="advanced", output_format="dict"
)
dict_narratives

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

[{'instance_index': 0,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.270\nPrediction Interval: [0.250, 0.278]\n\nFactors increasing Calibrated Probability:\nGlucose (145.0) > 127.50 — weight ≈ 0.038 [0.023, 0.092],\n\nFactors decreasing Calibrated Probability:\nBMI (22.2) <= 28.05 — weight ≈ -0.229 [-0.240, -0.219],\nInsulin (110.0) <= 192.50 — weight ≈ -0.180 [-0.194, -0.162],\nDiabetesPedigreeFunction (0.24) <= 0.57 — weight ≈ -0.180 [-0.194, -0.162],\nBloodPressure (82.0) > 74.50 — weight ≈ -0.174 [-0.192, -0.151],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 1,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.500\nPrediction Interval: [0.489, 0.510]\n\nFactors increasing Calibrated Probability:\nBMI (34.1) > 28.05 — weight ≈ 0.169 [0.160, 0.189],\nSkinThickness (0.0) <= 41.50 — weight ≈ 0.066 [0.040, 0.100],\nAge (38.0) > 28.50 — weight ≈ 0.050 [0.035, 0.067],\n\nFactors decreasing Calibrated Probability:\nGlucose (117.0) <= 127.50 — weight ≈ -0.190 [-0.260, -0.159],\nDiabetesPedigreeFunction (0.34) <= 0.57 — weight ≈ -0.020 [-0.042, -0.000],\nBloodPressure (92.0) > 74.50 — weight ≈ -0.011 [-0.030, 0.007], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 2,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.500\nPrediction Interval: [0.489, 0.510]\n\nFactors increasing Calibrated Probability:\nAge (60.0) > 28.50 — weight ≈ 0.334 [0.328, 0.363],\nBMI (36.0) > 28.05 — weight ≈ 0.276 [0.264, 0.321],\n\nFactors decreasing Calibrated Probability:\nGlucose (109.0) <= 127.50 — weight ≈ -0.363 [-0.438, -0.350],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 3,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.053\nPrediction Interval: [0.000, 0.056]\n\nFactors increasing Calibrated Probability:\nGlucose (108.0) <= 127.50 — weight ≈ -0.278 [-0.287, -0.258],\nBMI (26.0) <= 28.05 — weight ≈ -0.124 [-0.133, -0.086],\nAge (25.0) <= 28.50 — weight ≈ -0.114 [-0.127, -0.052],\nSkinThickness (24.0) <= 41.50 — weight ≈ -0.113 [-0.119, -0.084],\nPregnancies (3.0) <= 6.50 — weight ≈ -0.101 [-0.112, -0.052],\nBloodPressure (62.0) <= 74.50 — weight ≈ -0.059 [-0.067, 0.003], [⚠️ direction uncertain]\nDiabetesPedigreeFunction (0.22) <= 0.57 — weight ≈ -0.021 [-0.024, 0.017], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 4,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.500\nPrediction Interval: [0.489, 0.510]\n\nFactors increasing Calibrated Probability:\nBMI (32.0) > 28.05 — weight ≈ 0.169 [0.160, 0.189],\nGlucose (137.0) > 127.50 — weight ≈ 0.038 [0.022, 0.059],\nPregnancies (7.0) > 6.50 — weight ≈ 0.017 [0.005, 0.029],\nAge (39.0) > 28.50 — weight ≈ 0.017 [0.005, 0.029],\n\nFactors decreasing Calibrated Probability:\nDiabetesPedigreeFunction (0.39) <= 0.57 — weight ≈ -0.171 [-0.260, -0.134],\nBloodPressure (90.0) > 74.50 — weight ≈ -0.018 [-0.041, 0.003], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 5,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.270\nPrediction Interval: [0.250, 0.278]\n\nFactors increasing Calibrated Probability:\nBMI (30.0) > 28.05 — weight ≈ 0.123 [0.115, 0.174],\n\nFactors decreasing Calibrated Probability:\nGlucose (100.0) <= 127.50 — weight ≈ -0.419 [-0.489, -0.388],\nBloodPressure (0.0) <= 74.50 — weight ≈ -0.213 [-0.225, -0.200],\nSkinThickness (0.0) <= 41.50 — weight ≈ -0.180 [-0.194, -0.162],\nInsulin (0.0) <= 192.50 — weight ≈ -0.180 [-0.194, -0.162],\nDiabetesPedigreeFunction (0.48) <= 0.57 — weight ≈ -0.114 [-0.130, -0.091],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 6,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.500\nPrediction Interval: [0.489, 0.510]\n\nFactors increasing Calibrated Probability:\nGlucose (166.0) > 127.50 — weight ≈ 0.229 [0.222, 0.250],\nAge (51.0) > 28.50 — weight ≈ 0.033 [0.020, 0.048],\n\nFactors decreasing Calibrated Probability:\nBMI (25.8) <= 28.05 — weight ≈ -0.151 [-0.260, -0.105],\nPregnancies (5.0) <= 6.50 — weight ≈ -0.018 [-0.041, 0.003], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 7,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.520\nPrediction Interval: [0.500, 0.542]\n\nFactors increasing Calibrated Probability:\nGlucose (189.0) > 127.50 — weight ≈ 0.070 [0.056, 0.088],\nAge (59.0) > 28.50 — weight ≈ 0.037 [0.025, 0.050],\nBMI (30.1) > 28.05 — weight ≈ 0.020 [0.010, 0.031],\nInsulin (846.0) > 192.50 — weight ≈ 0.007 [-0.017, 0.030], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:\nPregnancies (1.0) <= 6.50 — weight ≈ -0.180 [-0.326, -0.118],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 8,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.882\nPrediction Interval: [0.875, 0.938]\n\nFactors increasing Calibrated Probability:\nGlucose (168.0) > 127.50 — weight ≈ 0.476 [0.465, 0.492],\nBMI (38.0) > 28.05 — weight ≈ 0.371 [0.352, 0.390],\nAge (34.0) > 28.50 — weight ≈ 0.077 [-0.055, 0.114], [⚠️ direction uncertain]\nSkinThickness (0.0) <= 41.50 — weight ≈ 0.069 [-0.055, 0.100], [⚠️ direction uncertain]\nInsulin (0.0) <= 192.50 — weight ≈ 0.011 [-0.055, 0.021], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:\nPregnancies (10.0) > 6.50 — weight ≈ -0.010 [-0.118, 0.003], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 9,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.270\nPrediction Interval: [0.250, 0.278]\n\nFactors increasing Calibrated Probability:\nPregnancies (8.0) > 6.50 — weight ≈ 0.047 [0.035, 0.092],\n\nFactors decreasing Calibrated Probability:\nBMI (0.0) <= 28.05 — weight ≈ -0.229 [-0.240, -0.219],\nAge (54.0) > 28.50 — weight ≈ -0.180 [-0.194, -0.162],\nGlucose (125.0) <= 127.50 — weight ≈ -0.114 [-0.130, -0.091],\nBloodPressure (96.0) > 74.50 — weight ≈ -0.054 [-0.068, -0.030],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'}]

In [25]:
# Different expertise levels:

# Single level
beginner_only = explanations.to_narrative(
    expertise_level="beginner", output_format="text"
)
print(beginner_only)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* Glucose (145.0) > 127.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 28.05,
* Insulin (110.0) <= 192.50,
* DiabetesPedigreeFunction (0.24) <= 0.57,
* BloodPressure (82.0) > 74.50,

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* BMI (34.1) > 28.05,
* SkinThickness (0.0) <= 41.50,
* Age (38.0) > 28.50,

Factors decreasing Calibrated Probability:
* Glucose (117.0) <= 127.50,
* DiabetesPedigreeFunction (0.34) <= 0.57,
* BloodPressure (92.0) > 74.50, [⚠️ direction uncertain]

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* Age (60.0) > 28.50,
* BMI (36.0) > 28.05,

Factors decreasing Calibrated Probability:
* Glucose (109.0) <= 127.50,

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.053

Factors increasing Calibrated Probability:
* Glucose (108.0) <= 127.50,
* BMI (26.0) <= 28.05,
* Age (25.0) <= 28.50,
* SkinThickness (24.0) <= 41.50,
* Pregnancies (3.0) <= 6.50,
* BloodPressure (62.0) <= 74.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.57, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* BMI (32.0) > 28.05,
* Glucose (137.0) > 127.50,
* Pregnancies (7.0) > 6.50,
* Age (39.0) > 28.50,

Factors decreasing Calibrated Probability:
* DiabetesPedigreeFunction (0.39) <= 0.57,
* BloodPressure (90.0) > 74.50, [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* BMI (30.0) > 28.05,

Factors decreasing Calibrated Probability:
* Glucose (100.0) <= 127.50,
* BloodPressure (0.0) <= 74.50,
* SkinThickness (0.0) <= 41.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.48) <= 0.57,

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.500

Factors increasing Calibrated Probability:
* Glucose (166.0) > 127.50,
* Age (51.0) > 28.50,

Factors decreasing Calibrated Probability:
* BMI (25.8) <= 28.05,
* Pregnancies (5.0) <= 6.50, [⚠️ direction uncertain]

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.520

Factors increasing Calibrated Probability:
* Glucose (189.0) > 127.50,
* Age (59.0) > 28.50,
* BMI (30.1) > 28.05,
* Insulin (846.0) > 192.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (1.0) <= 6.50,

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.882

Factors increasing Calibrated Probability:
* Glucose (168.0) > 127.50,
* BMI (38.0) > 28.05,
* Age (34.0) > 28.50, [⚠️ direction uncertain]
* SkinThickness (0.0) <= 41.50, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (10.0) > 6.50, [⚠️ direction uncertain]

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.270

Factors increasing Calibrated Probability:
* Pregnancies (8.0) > 6.50,

Factors decreasing Calibrated Probability:
* BMI (0.0) <= 28.05,
* Age (54.0) > 28.50,
* Glucose (125.0) <= 127.50,
* BloodPressure (96.0) > 74.50,

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [26]:
# Multiple levels
all_levels = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="dataframe",
)
all_levels

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_intermediate,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification

In [27]:
# Template path handling:

# If exp.yaml doesn't exist, automatically falls back to explain_template.yaml
narratives = explanations.to_narrative(
    template_path="exp.yaml",  # Will use default if not found
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)
narratives

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification

In [ ]:
# Use custom template
narratives = explanations.to_narrative(
    template_path="/path/to/custom_template.yaml",
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)

# Use default template
narratives = explanations.to_narrative(
    expertise_level=("beginner", "advanced"), output_format="dataframe"
)

print("The to_narrative method provides a clean, intuitive API for generating narratives!")

The to_narrative method provides a clean, intuitive API for generating narratives!

C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(
C:\Users\loftuw\Documents\Github\kristinebergs-calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(