In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
from pathlib import Path
# sys.path.insert(0, "/Users/poorna/Downloads/CE-updated/calibrated_explanations/src")

# Import the necessary libraries
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from calibrated_explanations import CalibratedExplainer, __version__

print(f"calibrated_explanations {__version__}")

calibrated_explanations v0.10.3

In [3]:
# Load and preprocess the data
num_to_test = 10  # number of instances to test, one from each class
dataset = "diabetes_full"
delimiter = ","
model = "RF"

filename = "../data/diabetes_full.csv"
df = pd.read_csv(filename, delimiter=delimiter)
target = "Y"
X, y = df.drop(target, axis=1), df[target]
no_of_classes = len(np.unique(y))
no_of_features = X.shape[1]
no_of_instances = X.shape[0]

# find categorical features
categorical_features = [i for i in range(no_of_features) if len(np.unique(X.iloc[:, i])) < 10]

# select test instances from each class and split into train, cal and test
idx = np.argsort(y.values).astype(int)
X, y = X.values[idx, :], y.values[idx]
test_index = np.array(
    [
        *range(int(num_to_test / 2)),
        *range(no_of_instances - 1, no_of_instances - int(num_to_test / 2) - 1, -1),
    ]
)
train_index = np.setdiff1d(np.array(range(no_of_instances)), test_index)
x_train, x_test = X[train_index, :], X[test_index, :]
y_train, y_test = y[train_index], y[test_index]
X_prop_train, x_cal, y_prop_train, y_cal = train_test_split(
    x_train, y_train, test_size=0.33, random_state=42, stratify=y_train
)

In [4]:
# Train the model and create the explainer
model = RandomForestClassifier()

model.fit(X_prop_train, y_prop_train)

ce = CalibratedExplainer(
    model,
    x_cal,
    y_cal,
    feature_names=df.columns,
    categorical_features=categorical_features,
    class_labels={0: "Non-diabetic", 1: "Diabetic"},
)

C:\Users\loftuw\CUDATemp\ipykernel_54568\2927877249.py:6: UserWarning: condition_source not provided; defaulting to 'prediction' in v0.10.3. Pass condition_source='observed' to retain previous behaviour.
  ce = CalibratedExplainer(

In [5]:
factual_explanations = ce.explain_factual(x_test)
print("Probability [lower and upper bound] for Diabetic:")
print(
    *zip(
        [
            f"Instance {i}: {exp.prediction['predict']:.3f} [{exp.prediction['low']:5.3f}, {exp.prediction['high']:5.3f}]"
            for i, exp in enumerate(factual_explanations)
        ]
    ),
    sep="\n",
)

Probability [lower and upper bound] for Diabetic:
('Instance 0: 0.348 [0.318, 0.364]',)
('Instance 1: 0.535 [0.500, 0.576]',)
('Instance 2: 0.452 [0.421, 0.478]',)
('Instance 3: 0.063 [0.043, 0.065]',)
('Instance 4: 0.562 [0.545, 0.583]',)
('Instance 5: 0.431 [0.409, 0.447]',)
('Instance 6: 0.476 [0.450, 0.500]',)
('Instance 7: 0.535 [0.500, 0.576]',)
('Instance 8: 0.727 [0.719, 0.750]',)
('Instance 9: 0.256 [0.237, 0.263]',)

Example demonstrating the new to_narrative API.

This shows the clean API for generating narratives from calibrated explanations.

In [6]:
template_path = "src/calibrated_explanations/templates/narrative_template.yaml"

# The new to_narrative method provides a clean API:
explanations = factual_explanations

# Basic usage
narratives = explanations[0].to_narrative(
    template_path=template_path,
    expertise_level=("beginner", "advanced"),
    output_format="text",
)
print(narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Advanced):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.348
Prediction Interval: [0.318, 0.364]

Factors increasing Calibrated Probability:
Glucose (145.0) > 121.50 — weight ≈ 0.127 [0.117, 0.170],
Pregnancies (13.0) > 6.50 — weight ≈ 0.060 [0.038, 0.111],

Factors decreasing Calibrated Probability:
BMI (22.2) <= 27.05 — weight ≈ -0.205 [-0.233, -0.182],
Insulin (110.0) <= 192.50 — weight ≈ -0.093 [-0.115, -0.066],
BloodPressure (82.0) > 71.00 — weight ≈ -0.089 [-0.108, -0.064],
SkinThickness (19.0) <= 32.50 — weight ≈ -0.083 [-0.100, -0.061],
DiabetesPedigreeFunction (0.24) <= 0.53 — weight ≈ -0.083 [-0.100, -0.061],
Age (57.0) > 28.50 — weight ≈ -0.028 [-0.044, -0.001],

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.348 [0.318, 0.364]

Factors increasing Calibrated Probability:
* Glucose (145.0) > 121.50,
* Pregnancies (13.0) > 6.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 27.05,
* Insulin (110.0) <= 192.50,
* BloodPressure (82.0) > 71.00,
* SkinThickness (19.0) <= 32.50,
* DiabetesPedigreeFunction (0.24) <= 0.53,
* Age (57.0) > 28.50,

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanation.py:512: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  result = plugin.plot(

In [7]:
# Different output formats:

# 1. DataFrame (default) - returns pandas DataFrame
df_narratives = explanations.to_narrative(
    template_path=template_path, expertise_level=("beginner", "advanced"), output_format="dataframe"
)
df_narratives

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification

In [8]:
# 2. Text - returns formatted text string
text_narratives = explanations.to_narrative(
    template_path=template_path, expertise_level="beginner", output_format="text"
)
print(text_narratives)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.348 [0.318, 0.364]

Factors increasing Calibrated Probability:
* Glucose (145.0) > 121.50,
* Pregnancies (13.0) > 6.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 27.05,
* Insulin (110.0) <= 192.50,
* BloodPressure (82.0) > 71.00,
* SkinThickness (19.0) <= 32.50,
* DiabetesPedigreeFunction (0.24) <= 0.53,
* Age (57.0) > 28.50,

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.535 [0.500, 0.576]

Factors increasing Calibrated Probability:
* BMI (34.1) > 27.05,
* Age (38.0) > 28.50,
* SkinThickness (0.0) <= 32.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.34) <= 0.53,

Factors decreasing Calibrated Probability:
* Glucose (117.0) <= 121.50,
* BloodPressure (92.0) > 71.00,
* Pregnancies (5.0) <= 6.50,

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.452 [0.421, 0.478]

Factors increasing Calibrated Probability:
* BMI (36.0) > 27.05,
* Age (60.0) > 28.50,
* DiabetesPedigreeFunction (0.55) > 0.53,

Factors decreasing Calibrated Probability:
* Glucose (109.0) <= 121.50,
* Pregnancies (5.0) <= 6.50,
* Insulin (0.0) <= 192.50,
* SkinThickness (26.0) <= 32.50, [⚠️ direction uncertain]
* BloodPressure (75.0) > 71.00, [⚠️ direction uncertain]

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.063 [0.043, 0.065]

Factors increasing Calibrated Probability:
* Glucose (108.0) <= 121.50,
* Age (25.0) <= 28.50,
* Pregnancies (3.0) <= 6.50,
* BMI (26.0) <= 27.05,
* SkinThickness (24.0) <= 32.50, [⚠️ direction uncertain]
* BloodPressure (62.0) <= 71.00, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.562 [0.545, 0.583]

Factors increasing Calibrated Probability:
* Glucose (137.0) > 121.50,
* BMI (32.0) > 27.05,
* Age (39.0) > 28.50,

Factors decreasing Calibrated Probability:
* SkinThickness (41.0) > 32.50,
* BloodPressure (90.0) > 71.00,
* DiabetesPedigreeFunction (0.39) <= 0.53, [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.431 [0.409, 0.447]

Factors increasing Calibrated Probability:
* BMI (30.0) > 27.05,
* Age (32.0) > 28.50,
* Pregnancies (7.0) > 6.50,
* SkinThickness (0.0) <= 32.50,

Factors decreasing Calibrated Probability:
* Glucose (100.0) <= 121.50,
* DiabetesPedigreeFunction (0.48) <= 0.53, [⚠️ direction uncertain]
* BloodPressure (0.0) <= 71.00, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.476 [0.450, 0.500]

Factors increasing Calibrated Probability:
* Glucose (166.0) > 121.50,
* Age (51.0) > 28.50,
* BloodPressure (72.0) > 71.00, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* BMI (25.8) <= 27.05,
* Pregnancies (5.0) <= 6.50,
* SkinThickness (19.0) <= 32.50,
* Insulin (175.0) <= 192.50,
* DiabetesPedigreeFunction (0.59) > 0.53, [⚠️ direction uncertain]

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.535 [0.500, 0.576]

Factors increasing Calibrated Probability:
* Glucose (189.0) > 121.50,
* BMI (30.1) > 27.05,
* Age (59.0) > 28.50,
* DiabetesPedigreeFunction (0.4) <= 0.53, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (1.0) <= 6.50,
* BloodPressure (60.0) <= 71.00,
* SkinThickness (23.0) <= 32.50,
* Insulin (846.0) > 192.50,

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.727 [0.719, 0.750]

Factors increasing Calibrated Probability:
* Glucose (168.0) > 121.50,
* BMI (38.0) > 27.05,
* DiabetesPedigreeFunction (0.54) > 0.53,
* BloodPressure (74.0) > 71.00, [⚠️ direction uncertain]
* SkinThickness (0.0) <= 32.50, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* Age (34.0) > 28.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (10.0) > 6.50, [⚠️ direction uncertain]

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.256 [0.237, 0.263]

Factors increasing Calibrated Probability:
* Glucose (125.0) > 121.50,

Factors decreasing Calibrated Probability:
* BMI (0.0) <= 27.05,
* Insulin (0.0) <= 192.50,
* SkinThickness (0.0) <= 32.50,
* BloodPressure (96.0) > 71.00,
* Age (54.0) > 28.50, [⚠️ direction uncertain]

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [9]:
# 3. HTML - returns HTML table
html_narratives = explanations.to_narrative(
    template_path=template_path,
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="html",
)
from IPython.display import HTML

HTML(html_narratives)

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [10]:
# 4. Dictionary - returns list of dictionaries
dict_narratives = explanations.to_narrative(
    template_path=template_path, expertise_level="advanced", output_format="dict"
)
dict_narratives

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

[{'instance_index': 0,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.348\nPrediction Interval: [0.318, 0.364]\n\nFactors increasing Calibrated Probability:\nGlucose (145.0) > 121.50 — weight ≈ 0.127 [0.117, 0.170],\nPregnancies (13.0) > 6.50 — weight ≈ 0.060 [0.038, 0.111],\n\nFactors decreasing Calibrated Probability:\nBMI (22.2) <= 27.05 — weight ≈ -0.205 [-0.233, -0.182],\nInsulin (110.0) <= 192.50 — weight ≈ -0.093 [-0.115, -0.066],\nBloodPressure (82.0) > 71.00 — weight ≈ -0.089 [-0.108, -0.064],\nSkinThickness (19.0) <= 32.50 — weight ≈ -0.083 [-0.100, -0.061],\nDiabetesPedigreeFunction (0.24) <= 0.53 — weight ≈ -0.083 [-0.100, -0.061],\nAge (57.0) > 28.50 — weight ≈ -0.028 [-0.044, -0.001],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 1,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.535\nPrediction Interval: [0.500, 0.576]\n\nFactors increasing Calibrated Probability:\nBMI (34.1) > 27.05 — weight ≈ 0.279 [0.272, 0.298],\nAge (38.0) > 28.50 — weight ≈ 0.187 [0.172, 0.217],\nSkinThickness (0.0) <= 32.50 — weight ≈ 0.104 [0.088, 0.126],\nInsulin (0.0) <= 192.50 — weight ≈ 0.059 [0.035, 0.085],\nDiabetesPedigreeFunction (0.34) <= 0.53 — weight ≈ 0.039 [0.010, 0.069],\n\nFactors decreasing Calibrated Probability:\nGlucose (117.0) <= 121.50 — weight ≈ -0.192 [-0.215, -0.184],\nBloodPressure (92.0) > 71.00 — weight ≈ -0.106 [-0.159, -0.077],\nPregnancies (5.0) <= 6.50 — weight ≈ -0.024 [-0.048, -0.006],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 2,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.452\nPrediction Interval: [0.421, 0.478]\n\nFactors increasing Calibrated Probability:\nBMI (36.0) > 27.05 — weight ≈ 0.196 [0.189, 0.216],\nAge (60.0) > 28.50 — weight ≈ 0.196 [0.189, 0.216],\nDiabetesPedigreeFunction (0.55) > 0.53 — weight ≈ 0.077 [0.061, 0.104],\n\nFactors decreasing Calibrated Probability:\nGlucose (109.0) <= 121.50 — weight ≈ -0.257 [-0.298, -0.240],\nPregnancies (5.0) <= 6.50 — weight ≈ -0.107 [-0.131, -0.088],\nInsulin (0.0) <= 192.50 — weight ≈ -0.098 [-0.128, -0.073],\nSkinThickness (26.0) <= 32.50 — weight ≈ -0.021 [-0.048, 0.010], [⚠️ direction uncertain]\nBloodPressure (75.0) > 71.00 — weight ≈ -0.015 [-0.038, 0.012], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 3,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.063\nPrediction Interval: [0.043, 0.065]\n\nFactors increasing Calibrated Probability:\nGlucose (108.0) <= 121.50 — weight ≈ -0.224 [-0.233, -0.201],\nAge (25.0) <= 28.50 — weight ≈ -0.204 [-0.215, -0.174],\nPregnancies (3.0) <= 6.50 — weight ≈ -0.129 [-0.134, -0.109],\nBMI (26.0) <= 27.05 — weight ≈ -0.099 [-0.108, -0.050],\nSkinThickness (24.0) <= 32.50 — weight ≈ -0.061 [-0.071, 0.004], [⚠️ direction uncertain]\nBloodPressure (62.0) <= 71.00 — weight ≈ -0.007 [-0.009, 0.020], [⚠️ direction uncertain]\nInsulin (0.0) <= 192.50 — weight ≈ -0.003 [-0.005, 0.020], [⚠️ direction uncertain]\nDiabetesPedigreeFunction (0.22) <= 0.53 — weight ≈ -0.000 [-0.002, 0.020], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 4,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.562\nPrediction Interval: [0.545, 0.583]\n\nFactors increasing Calibrated Probability:\nGlucose (137.0) > 121.50 — weight ≈ 0.205 [0.186, 0.234],\nBMI (32.0) > 27.05 — weight ≈ 0.187 [0.170, 0.214],\nAge (39.0) > 28.50 — weight ≈ 0.116 [0.091, 0.145],\n\nFactors decreasing Calibrated Probability:\nSkinThickness (41.0) > 32.50 — weight ≈ -0.110 [-0.132, -0.099],\nBloodPressure (90.0) > 71.00 — weight ≈ -0.079 [-0.132, -0.051],\nDiabetesPedigreeFunction (0.39) <= 0.53 — weight ≈ -0.023 [-0.077, 0.012], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 5,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.431\nPrediction Interval: [0.409, 0.447]\n\nFactors increasing Calibrated Probability:\nBMI (30.0) > 27.05 — weight ≈ 0.174 [0.168, 0.194],\nAge (32.0) > 28.50 — weight ≈ 0.169 [0.160, 0.194],\nPregnancies (7.0) > 6.50 — weight ≈ 0.083 [0.067, 0.113],\nSkinThickness (0.0) <= 32.50 — weight ≈ 0.028 [0.011, 0.052],\n\nFactors decreasing Calibrated Probability:\nGlucose (100.0) <= 121.50 — weight ≈ -0.296 [-0.319, -0.288],\nDiabetesPedigreeFunction (0.48) <= 0.53 — weight ≈ -0.026 [-0.050, 0.002], [⚠️ direction uncertain]\nBloodPressure (0.0) <= 71.00 — weight ≈ -0.024 [-0.052, 0.009], [⚠️ direction uncertain]\nInsulin (0.0) <= 192.50 — weight ≈ -0.000 [-0.017, 0.022], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 6,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.476\nPrediction Interval: [0.450, 0.500]\n\nFactors increasing Calibrated Probability:\nGlucose (166.0) > 121.50 — weight ≈ 0.184 [0.172, 0.212],\nAge (51.0) > 28.50 — weight ≈ 0.030 [0.010, 0.053],\nBloodPressure (72.0) > 71.00 — weight ≈ 0.000 [-0.024, 0.026], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:\nBMI (25.8) <= 27.05 — weight ≈ -0.115 [-0.163, -0.085],\nPregnancies (5.0) <= 6.50 — weight ≈ -0.086 [-0.107, -0.069],\nSkinThickness (19.0) <= 32.50 — weight ≈ -0.083 [-0.107, -0.065],\nInsulin (175.0) <= 192.50 — weight ≈ -0.082 [-0.107, -0.062],\nDiabetesPedigreeFunction (0.59) > 0.53 — weight ≈ -0.020 [-0.049, 0.010], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 7,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.535\nPrediction Interval: [0.500, 0.576]\n\nFactors increasing Calibrated Probability:\nGlucose (189.0) > 121.50 — weight ≈ 0.199 [0.179, 0.241],\nBMI (30.1) > 27.05 — weight ≈ 0.088 [0.065, 0.117],\nAge (59.0) > 28.50 — weight ≈ 0.059 [0.030, 0.091],\nDiabetesPedigreeFunction (0.4) <= 0.53 — weight ≈ 0.011 [-0.018, 0.037], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:\nPregnancies (1.0) <= 6.50 — weight ≈ -0.186 [-0.215, -0.175],\nBloodPressure (60.0) <= 71.00 — weight ≈ -0.050 [-0.104, -0.015],\nSkinThickness (23.0) <= 32.50 — weight ≈ -0.027 [-0.048, -0.010],\nInsulin (846.0) > 192.50 — weight ≈ -0.023 [-0.048, -0.003],',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 8,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.727\nPrediction Interval: [0.719, 0.750]\n\nFactors increasing Calibrated Probability:\nGlucose (168.0) > 121.50 — weight ≈ 0.238 [0.217, 0.259],\nBMI (38.0) > 27.05 — weight ≈ 0.212 [0.177, 0.244],\nDiabetesPedigreeFunction (0.54) > 0.53 — weight ≈ 0.090 [0.061, 0.107],\nBloodPressure (74.0) > 71.00 — weight ≈ 0.012 [-0.023, 0.026], [⚠️ direction uncertain]\nSkinThickness (0.0) <= 32.50 — weight ≈ 0.000 [-0.023, 0.009], [⚠️ direction uncertain]\nInsulin (0.0) <= 192.50 — weight ≈ 0.000 [-0.023, 0.009], [⚠️ direction uncertain]\nAge (34.0) > 28.50 — weight ≈ 0.000 [-0.023, 0.009], [⚠️ direction uncertain]\n\nFactors decreasing Calibrated Probability:\nPregnancies (10.0) > 6.50 — weight ≈ -0.021 [-0.106, 0.003], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'},
 {'instance_index': 9,
  'factual_explanation_advanced': 'Prediction: Diabetic\nCalibrated Probability: 0.256\nPrediction Interval: [0.237, 0.263]\n\nFactors increasing Calibrated Probability:\nGlucose (125.0) > 121.50 — weight ≈ 0.097 [0.090, 0.138],\n\nFactors decreasing Calibrated Probability:\nBMI (0.0) <= 27.05 — weight ≈ -0.297 [-0.324, -0.274],\nInsulin (0.0) <= 192.50 — weight ≈ -0.174 [-0.191, -0.153],\nSkinThickness (0.0) <= 32.50 — weight ≈ -0.077 [-0.097, -0.035],\nBloodPressure (96.0) > 71.00 — weight ≈ -0.052 [-0.071, -0.008],\nAge (54.0) > 28.50 — weight ≈ -0.037 [-0.061, 0.020], [⚠️ direction uncertain]',
  'expertise_level': ('advanced',),
  'problem_type': 'binary_classification'}]

In [11]:
# Different expertise levels:

# Single level
beginner_only = explanations.to_narrative(
    expertise_level="beginner", output_format="text", template_path=template_path
)
print(beginner_only)

================================================================================
Instance 0
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.348 [0.318, 0.364]

Factors increasing Calibrated Probability:
* Glucose (145.0) > 121.50,
* Pregnancies (13.0) > 6.50,

Factors decreasing Calibrated Probability:
* BMI (22.2) <= 27.05,
* Insulin (110.0) <= 192.50,
* BloodPressure (82.0) > 71.00,
* SkinThickness (19.0) <= 32.50,
* DiabetesPedigreeFunction (0.24) <= 0.53,
* Age (57.0) > 28.50,

================================================================================
Instance 1
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.535 [0.500, 0.576]

Factors increasing Calibrated Probability:
* BMI (34.1) > 27.05,
* Age (38.0) > 28.50,
* SkinThickness (0.0) <= 32.50,
* Insulin (0.0) <= 192.50,
* DiabetesPedigreeFunction (0.34) <= 0.53,

Factors decreasing Calibrated Probability:
* Glucose (117.0) <= 121.50,
* BloodPressure (92.0) > 71.00,
* Pregnancies (5.0) <= 6.50,

================================================================================
Instance 2
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.452 [0.421, 0.478]

Factors increasing Calibrated Probability:
* BMI (36.0) > 27.05,
* Age (60.0) > 28.50,
* DiabetesPedigreeFunction (0.55) > 0.53,

Factors decreasing Calibrated Probability:
* Glucose (109.0) <= 121.50,
* Pregnancies (5.0) <= 6.50,
* Insulin (0.0) <= 192.50,
* SkinThickness (26.0) <= 32.50, [⚠️ direction uncertain]
* BloodPressure (75.0) > 71.00, [⚠️ direction uncertain]

================================================================================
Instance 3
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.063 [0.043, 0.065]

Factors increasing Calibrated Probability:
* Glucose (108.0) <= 121.50,
* Age (25.0) <= 28.50,
* Pregnancies (3.0) <= 6.50,
* BMI (26.0) <= 27.05,
* SkinThickness (24.0) <= 32.50, [⚠️ direction uncertain]
* BloodPressure (62.0) <= 71.00, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* DiabetesPedigreeFunction (0.22) <= 0.53, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:

================================================================================
Instance 4
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.562 [0.545, 0.583]

Factors increasing Calibrated Probability:
* Glucose (137.0) > 121.50,
* BMI (32.0) > 27.05,
* Age (39.0) > 28.50,

Factors decreasing Calibrated Probability:
* SkinThickness (41.0) > 32.50,
* BloodPressure (90.0) > 71.00,
* DiabetesPedigreeFunction (0.39) <= 0.53, [⚠️ direction uncertain]

================================================================================
Instance 5
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.431 [0.409, 0.447]

Factors increasing Calibrated Probability:
* BMI (30.0) > 27.05,
* Age (32.0) > 28.50,
* Pregnancies (7.0) > 6.50,
* SkinThickness (0.0) <= 32.50,

Factors decreasing Calibrated Probability:
* Glucose (100.0) <= 121.50,
* DiabetesPedigreeFunction (0.48) <= 0.53, [⚠️ direction uncertain]
* BloodPressure (0.0) <= 71.00, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]

================================================================================
Instance 6
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.476 [0.450, 0.500]

Factors increasing Calibrated Probability:
* Glucose (166.0) > 121.50,
* Age (51.0) > 28.50,
* BloodPressure (72.0) > 71.00, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* BMI (25.8) <= 27.05,
* Pregnancies (5.0) <= 6.50,
* SkinThickness (19.0) <= 32.50,
* Insulin (175.0) <= 192.50,
* DiabetesPedigreeFunction (0.59) > 0.53, [⚠️ direction uncertain]

================================================================================
Instance 7
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.535 [0.500, 0.576]

Factors increasing Calibrated Probability:
* Glucose (189.0) > 121.50,
* BMI (30.1) > 27.05,
* Age (59.0) > 28.50,
* DiabetesPedigreeFunction (0.4) <= 0.53, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (1.0) <= 6.50,
* BloodPressure (60.0) <= 71.00,
* SkinThickness (23.0) <= 32.50,
* Insulin (846.0) > 192.50,

================================================================================
Instance 8
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.727 [0.719, 0.750]

Factors increasing Calibrated Probability:
* Glucose (168.0) > 121.50,
* BMI (38.0) > 27.05,
* DiabetesPedigreeFunction (0.54) > 0.53,
* BloodPressure (74.0) > 71.00, [⚠️ direction uncertain]
* SkinThickness (0.0) <= 32.50, [⚠️ direction uncertain]
* Insulin (0.0) <= 192.50, [⚠️ direction uncertain]
* Age (34.0) > 28.50, [⚠️ direction uncertain]

Factors decreasing Calibrated Probability:
* Pregnancies (10.0) > 6.50, [⚠️ direction uncertain]

================================================================================
Instance 9
================================================================================

Factual Explanation (Beginner):
--------------------------------------------------------------------------------
Prediction: Diabetic
Calibrated Probability: 0.256 [0.237, 0.263]

Factors increasing Calibrated Probability:
* Glucose (125.0) > 121.50,

Factors decreasing Calibrated Probability:
* BMI (0.0) <= 27.05,
* Insulin (0.0) <= 192.50,
* SkinThickness (0.0) <= 32.50,
* BloodPressure (96.0) > 71.00,
* Age (54.0) > 28.50, [⚠️ direction uncertain]

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

In [12]:
# Multiple levels
all_levels = explanations.to_narrative(
    expertise_level=("beginner", "intermediate", "advanced"),
    output_format="dataframe",
    template_path=template_path,
)
all_levels

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_intermediate,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, intermediate, advanced)",binary_classification

In [13]:
# Template path handling:

# If exp.yaml doesn't exist, automatically falls back to explain_template.yaml
narratives = explanations.to_narrative(
    template_path="exp.yaml",  # Will use default if not found
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)
narratives

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(

,instance_index,factual_explanation_beginner,factual_explanation_advanced,expertise_level,problem_type
0,0,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
1,1,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
2,2,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
3,3,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
4,4,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
5,5,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
6,6,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
7,7,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
8,8,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification
9,9,Prediction: Diabetic\nCalibrated Probability: ...,Prediction: Diabetic\nCalibrated Probability: ...,"(beginner, advanced)",binary_classification

In [14]:
# Use custom template
narratives = explanations.to_narrative(
    template_path="/path/to/custom_template.yaml",
    expertise_level=("beginner", "advanced"),
    output_format="dataframe",
)

# Use default template explicitly
narratives = explanations.to_narrative(
    template_path=template_path, expertise_level=("beginner", "advanced"), output_format="dataframe"
)

print("The to_narrative method provides a clean, intuitive API for generating narratives!")

The to_narrative method provides a clean, intuitive API for generating narratives!

C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(
C:\Users\loftuw\Documents\Github\calibrated_explanations\src\calibrated_explanations\explanations\explanations.py:1270: UserWarning: Narrative template fallback: default template used because provided relative path was missing
  return plugin.plot(